/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_HelloWorld_EventTriggerDefinition;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_HelloWorld_ActionDefinition;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_HelloWorld_IndicationHeader;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_HelloWorld_IndicationMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_HelloWorld_ControlHeader;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_HelloWorld_ControlMessage;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module E2SM-HelloWorld-IEs in e2sm-HelloWorld-v001.asn */
	&asn_DEF_E2SM_HelloWorld_EventTriggerDefinition,	
	&asn_DEF_E2SM_HelloWorld_ActionDefinition,	
	&asn_DEF_E2SM_HelloWorld_IndicationHeader,	
	&asn_DEF_E2SM_HelloWorld_IndicationMessage,	
	&asn_DEF_E2SM_HelloWorld_ControlHeader,	
	&asn_DEF_E2SM_HelloWorld_ControlMessage,	
	0
};

