/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "../../asn_defs/asn1/e2ap-v031-subset.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_RICindicationMessage_H_
#define	_E2N_RICindicationMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E2N_RICindicationMessage */
typedef OCTET_STRING_t	 E2N_RICindicationMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2N_RICindicationMessage;
asn_struct_free_f E2N_RICindicationMessage_free;
asn_struct_print_f E2N_RICindicationMessage_print;
asn_constr_check_f E2N_RICindicationMessage_constraint;
ber_type_decoder_f E2N_RICindicationMessage_decode_ber;
der_type_encoder_f E2N_RICindicationMessage_encode_der;
xer_type_decoder_f E2N_RICindicationMessage_decode_xer;
xer_type_encoder_f E2N_RICindicationMessage_encode_xer;
per_type_decoder_f E2N_RICindicationMessage_decode_uper;
per_type_encoder_f E2N_RICindicationMessage_encode_uper;
per_type_decoder_f E2N_RICindicationMessage_decode_aper;
per_type_encoder_f E2N_RICindicationMessage_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_RICindicationMessage_H_ */
#include <asn_internal.h>
