/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-IEs"
 * 	found in "../../asn_defs/asn1/e2ap-v031-subset.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_RICsubsequentAction_H_
#define	_E2N_RICsubsequentAction_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E2N_RICsubsequentActionType.h"
#include "E2N_RICtimeToWait.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E2N_RICsubsequentAction */
typedef struct E2N_RICsubsequentAction {
	E2N_RICsubsequentActionType_t	 ricSubsequentActionType;
	E2N_RICtimeToWait_t	 ricTimeToWait;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_RICsubsequentAction_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2N_RICsubsequentAction;
extern asn_SEQUENCE_specifics_t asn_SPC_E2N_RICsubsequentAction_specs_1;
extern asn_TYPE_member_t asn_MBR_E2N_RICsubsequentAction_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_RICsubsequentAction_H_ */
#include <asn_internal.h>
