/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Descriptions"
 * 	found in "../../asn_defs/asn1/e2ap-v031-subset.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_SuccessfulOutcome_H_
#define	_E2N_SuccessfulOutcome_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E2N_ProcedureCode.h"
#include "E2N_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "E2N_RICsubscriptionRequest.h"
#include "E2N_RICsubscriptionResponse.h"
#include "E2N_RICsubscriptionFailure.h"
#include "E2N_RICsubscriptionDeleteRequest.h"
#include "E2N_RICsubscriptionDeleteResponse.h"
#include "E2N_RICsubscriptionDeleteFailure.h"
#include "E2N_RICserviceUpdate.h"
#include "E2N_RICserviceUpdateAcknowledge.h"
#include "E2N_RICserviceUpdateFailure.h"
#include "E2N_RICcontrolRequest.h"
#include "E2N_RICcontrolAcknowledge.h"
#include "E2N_RICcontrolFailure.h"
#include "E2N_RICindication.h"
#include "E2N_RICserviceQuery.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2N_SuccessfulOutcome__value_PR {
	E2N_SuccessfulOutcome__value_PR_NOTHING,	/* No components present */
	E2N_SuccessfulOutcome__value_PR_RICsubscriptionResponse,
	E2N_SuccessfulOutcome__value_PR_RICsubscriptionDeleteResponse,
	E2N_SuccessfulOutcome__value_PR_RICserviceUpdateAcknowledge,
	E2N_SuccessfulOutcome__value_PR_RICcontrolAcknowledge
} E2N_SuccessfulOutcome__value_PR;

/* E2N_SuccessfulOutcome */
typedef struct E2N_SuccessfulOutcome {
	E2N_ProcedureCode_t	 procedureCode;
	E2N_Criticality_t	 criticality;
	struct E2N_SuccessfulOutcome__value {
		E2N_SuccessfulOutcome__value_PR present;
		union E2N_SuccessfulOutcome__E2N_value_u {
			E2N_RICsubscriptionResponse_t	 RICsubscriptionResponse;
			E2N_RICsubscriptionDeleteResponse_t	 RICsubscriptionDeleteResponse;
			E2N_RICserviceUpdateAcknowledge_t	 RICserviceUpdateAcknowledge;
			E2N_RICcontrolAcknowledge_t	 RICcontrolAcknowledge;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_SuccessfulOutcome_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2N_SuccessfulOutcome;
extern asn_SEQUENCE_specifics_t asn_SPC_E2N_SuccessfulOutcome_specs_1;
extern asn_TYPE_member_t asn_MBR_E2N_SuccessfulOutcome_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_SuccessfulOutcome_H_ */
#include <asn_internal.h>
