/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-Containers"
 * 	found in "../../asn_defs/asn1/X2AP-minimized.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#include "E2N_ProtocolExtensionField.h"

static int
memb_E2N_id_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_E2N_criticality_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_E2N_extensionValue_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_E2N_id_constraint_5(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_E2N_criticality_constraint_5(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_E2N_extensionValue_constraint_5(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_E2N_id_constraint_9(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_E2N_criticality_constraint_9(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_E2N_extensionValue_constraint_9(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_E2N_id_constraint_13(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 65535)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_E2N_criticality_constraint_13(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_E2N_extensionValue_constraint_13(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_per_constraints_t asn_PER_memb_E2N_id_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2N_criticality_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2N_extensionValue_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2N_id_constr_6 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2N_criticality_constr_7 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2N_extensionValue_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2N_id_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2N_criticality_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2N_extensionValue_constr_12 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2N_id_constr_14 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 16,  16,  0,  65535 }	/* (0..65535) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2N_criticality_constr_15 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_E2N_extensionValue_constr_16 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_CHOICE_specifics_t asn_SPC_E2N_extensionValue_specs_4 = {
	sizeof(struct E2N_CriticalityDiagnostics_ExtIEs__extensionValue),
	offsetof(struct E2N_CriticalityDiagnostics_ExtIEs__extensionValue, _asn_ctx),
	offsetof(struct E2N_CriticalityDiagnostics_ExtIEs__extensionValue, present),
	sizeof(((struct E2N_CriticalityDiagnostics_ExtIEs__extensionValue *)0)->present),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_E2N_extensionValue_4 = {
	"extensionValue",
	"extensionValue",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	0, 0,	/* No members */
	&asn_SPC_E2N_extensionValue_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2N_CriticalityDiagnostics_ExtIEs_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2N_CriticalityDiagnostics_ExtIEs, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2N_ProtocolIE_ID,
		0,
		{ 0, &asn_PER_memb_E2N_id_constr_2,  memb_E2N_id_constraint_1 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2N_CriticalityDiagnostics_ExtIEs, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2N_Criticality,
		0,
		{ 0, &asn_PER_memb_E2N_criticality_constr_3,  memb_E2N_criticality_constraint_1 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct E2N_CriticalityDiagnostics_ExtIEs, extensionValue),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_E2N_extensionValue_4,
		0,
		{ 0, &asn_PER_memb_E2N_extensionValue_constr_4,  memb_E2N_extensionValue_constraint_1 },
		0, 0, /* No default value */
		"extensionValue"
		},
};
static const ber_tlv_tag_t asn_DEF_E2N_CriticalityDiagnostics_ExtIEs_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2N_CriticalityDiagnostics_ExtIEs_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* extensionValue */
};
asn_SEQUENCE_specifics_t asn_SPC_E2N_CriticalityDiagnostics_ExtIEs_specs_1 = {
	sizeof(struct E2N_CriticalityDiagnostics_ExtIEs),
	offsetof(struct E2N_CriticalityDiagnostics_ExtIEs, _asn_ctx),
	asn_MAP_E2N_CriticalityDiagnostics_ExtIEs_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2N_CriticalityDiagnostics_ExtIEs = {
	"CriticalityDiagnostics-ExtIEs",
	"CriticalityDiagnostics-ExtIEs",
	&asn_OP_SEQUENCE,
	asn_DEF_E2N_CriticalityDiagnostics_ExtIEs_tags_1,
	sizeof(asn_DEF_E2N_CriticalityDiagnostics_ExtIEs_tags_1)
		/sizeof(asn_DEF_E2N_CriticalityDiagnostics_ExtIEs_tags_1[0]), /* 1 */
	asn_DEF_E2N_CriticalityDiagnostics_ExtIEs_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2N_CriticalityDiagnostics_ExtIEs_tags_1)
		/sizeof(asn_DEF_E2N_CriticalityDiagnostics_ExtIEs_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2N_CriticalityDiagnostics_ExtIEs_1,
	3,	/* Elements count */
	&asn_SPC_E2N_CriticalityDiagnostics_ExtIEs_specs_1	/* Additional specs */
};

static asn_CHOICE_specifics_t asn_SPC_E2N_extensionValue_specs_8 = {
	sizeof(struct E2N_CriticalityDiagnostics_IE_List_ExtIEs__extensionValue),
	offsetof(struct E2N_CriticalityDiagnostics_IE_List_ExtIEs__extensionValue, _asn_ctx),
	offsetof(struct E2N_CriticalityDiagnostics_IE_List_ExtIEs__extensionValue, present),
	sizeof(((struct E2N_CriticalityDiagnostics_IE_List_ExtIEs__extensionValue *)0)->present),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_E2N_extensionValue_8 = {
	"extensionValue",
	"extensionValue",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	0, 0,	/* No members */
	&asn_SPC_E2N_extensionValue_specs_8	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2N_CriticalityDiagnostics_IE_List_ExtIEs_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2N_CriticalityDiagnostics_IE_List_ExtIEs, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2N_ProtocolIE_ID,
		0,
		{ 0, &asn_PER_memb_E2N_id_constr_6,  memb_E2N_id_constraint_5 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2N_CriticalityDiagnostics_IE_List_ExtIEs, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2N_Criticality,
		0,
		{ 0, &asn_PER_memb_E2N_criticality_constr_7,  memb_E2N_criticality_constraint_5 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct E2N_CriticalityDiagnostics_IE_List_ExtIEs, extensionValue),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_E2N_extensionValue_8,
		0,
		{ 0, &asn_PER_memb_E2N_extensionValue_constr_8,  memb_E2N_extensionValue_constraint_5 },
		0, 0, /* No default value */
		"extensionValue"
		},
};
static const ber_tlv_tag_t asn_DEF_E2N_CriticalityDiagnostics_IE_List_ExtIEs_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2N_CriticalityDiagnostics_IE_List_ExtIEs_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* extensionValue */
};
asn_SEQUENCE_specifics_t asn_SPC_E2N_CriticalityDiagnostics_IE_List_ExtIEs_specs_5 = {
	sizeof(struct E2N_CriticalityDiagnostics_IE_List_ExtIEs),
	offsetof(struct E2N_CriticalityDiagnostics_IE_List_ExtIEs, _asn_ctx),
	asn_MAP_E2N_CriticalityDiagnostics_IE_List_ExtIEs_tag2el_5,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2N_CriticalityDiagnostics_IE_List_ExtIEs = {
	"CriticalityDiagnostics-IE-List-ExtIEs",
	"CriticalityDiagnostics-IE-List-ExtIEs",
	&asn_OP_SEQUENCE,
	asn_DEF_E2N_CriticalityDiagnostics_IE_List_ExtIEs_tags_5,
	sizeof(asn_DEF_E2N_CriticalityDiagnostics_IE_List_ExtIEs_tags_5)
		/sizeof(asn_DEF_E2N_CriticalityDiagnostics_IE_List_ExtIEs_tags_5[0]), /* 1 */
	asn_DEF_E2N_CriticalityDiagnostics_IE_List_ExtIEs_tags_5,	/* Same as above */
	sizeof(asn_DEF_E2N_CriticalityDiagnostics_IE_List_ExtIEs_tags_5)
		/sizeof(asn_DEF_E2N_CriticalityDiagnostics_IE_List_ExtIEs_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2N_CriticalityDiagnostics_IE_List_ExtIEs_5,
	3,	/* Elements count */
	&asn_SPC_E2N_CriticalityDiagnostics_IE_List_ExtIEs_specs_5	/* Additional specs */
};

static asn_CHOICE_specifics_t asn_SPC_E2N_extensionValue_specs_12 = {
	sizeof(struct E2N_GlobalENB_ID_ExtIEs__extensionValue),
	offsetof(struct E2N_GlobalENB_ID_ExtIEs__extensionValue, _asn_ctx),
	offsetof(struct E2N_GlobalENB_ID_ExtIEs__extensionValue, present),
	sizeof(((struct E2N_GlobalENB_ID_ExtIEs__extensionValue *)0)->present),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_E2N_extensionValue_12 = {
	"extensionValue",
	"extensionValue",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	0, 0,	/* No members */
	&asn_SPC_E2N_extensionValue_specs_12	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2N_GlobalENB_ID_ExtIEs_9[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2N_GlobalENB_ID_ExtIEs, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2N_ProtocolIE_ID,
		0,
		{ 0, &asn_PER_memb_E2N_id_constr_10,  memb_E2N_id_constraint_9 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2N_GlobalENB_ID_ExtIEs, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2N_Criticality,
		0,
		{ 0, &asn_PER_memb_E2N_criticality_constr_11,  memb_E2N_criticality_constraint_9 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct E2N_GlobalENB_ID_ExtIEs, extensionValue),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_E2N_extensionValue_12,
		0,
		{ 0, &asn_PER_memb_E2N_extensionValue_constr_12,  memb_E2N_extensionValue_constraint_9 },
		0, 0, /* No default value */
		"extensionValue"
		},
};
static const ber_tlv_tag_t asn_DEF_E2N_GlobalENB_ID_ExtIEs_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2N_GlobalENB_ID_ExtIEs_tag2el_9[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* extensionValue */
};
asn_SEQUENCE_specifics_t asn_SPC_E2N_GlobalENB_ID_ExtIEs_specs_9 = {
	sizeof(struct E2N_GlobalENB_ID_ExtIEs),
	offsetof(struct E2N_GlobalENB_ID_ExtIEs, _asn_ctx),
	asn_MAP_E2N_GlobalENB_ID_ExtIEs_tag2el_9,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2N_GlobalENB_ID_ExtIEs = {
	"GlobalENB-ID-ExtIEs",
	"GlobalENB-ID-ExtIEs",
	&asn_OP_SEQUENCE,
	asn_DEF_E2N_GlobalENB_ID_ExtIEs_tags_9,
	sizeof(asn_DEF_E2N_GlobalENB_ID_ExtIEs_tags_9)
		/sizeof(asn_DEF_E2N_GlobalENB_ID_ExtIEs_tags_9[0]), /* 1 */
	asn_DEF_E2N_GlobalENB_ID_ExtIEs_tags_9,	/* Same as above */
	sizeof(asn_DEF_E2N_GlobalENB_ID_ExtIEs_tags_9)
		/sizeof(asn_DEF_E2N_GlobalENB_ID_ExtIEs_tags_9[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2N_GlobalENB_ID_ExtIEs_9,
	3,	/* Elements count */
	&asn_SPC_E2N_GlobalENB_ID_ExtIEs_specs_9	/* Additional specs */
};

static asn_CHOICE_specifics_t asn_SPC_E2N_extensionValue_specs_16 = {
	sizeof(struct E2N_GlobalGNB_ID_ExtIEs__extensionValue),
	offsetof(struct E2N_GlobalGNB_ID_ExtIEs__extensionValue, _asn_ctx),
	offsetof(struct E2N_GlobalGNB_ID_ExtIEs__extensionValue, present),
	sizeof(((struct E2N_GlobalGNB_ID_ExtIEs__extensionValue *)0)->present),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_E2N_extensionValue_16 = {
	"extensionValue",
	"extensionValue",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	0, 0,	/* No members */
	&asn_SPC_E2N_extensionValue_specs_16	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2N_GlobalGNB_ID_ExtIEs_13[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2N_GlobalGNB_ID_ExtIEs, id),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2N_ProtocolIE_ID,
		0,
		{ 0, &asn_PER_memb_E2N_id_constr_14,  memb_E2N_id_constraint_13 },
		0, 0, /* No default value */
		"id"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2N_GlobalGNB_ID_ExtIEs, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2N_Criticality,
		0,
		{ 0, &asn_PER_memb_E2N_criticality_constr_15,  memb_E2N_criticality_constraint_13 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct E2N_GlobalGNB_ID_ExtIEs, extensionValue),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_E2N_extensionValue_16,
		0,
		{ 0, &asn_PER_memb_E2N_extensionValue_constr_16,  memb_E2N_extensionValue_constraint_13 },
		0, 0, /* No default value */
		"extensionValue"
		},
};
static const ber_tlv_tag_t asn_DEF_E2N_GlobalGNB_ID_ExtIEs_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2N_GlobalGNB_ID_ExtIEs_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* id */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* extensionValue */
};
asn_SEQUENCE_specifics_t asn_SPC_E2N_GlobalGNB_ID_ExtIEs_specs_13 = {
	sizeof(struct E2N_GlobalGNB_ID_ExtIEs),
	offsetof(struct E2N_GlobalGNB_ID_ExtIEs, _asn_ctx),
	asn_MAP_E2N_GlobalGNB_ID_ExtIEs_tag2el_13,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2N_GlobalGNB_ID_ExtIEs = {
	"GlobalGNB-ID-ExtIEs",
	"GlobalGNB-ID-ExtIEs",
	&asn_OP_SEQUENCE,
	asn_DEF_E2N_GlobalGNB_ID_ExtIEs_tags_13,
	sizeof(asn_DEF_E2N_GlobalGNB_ID_ExtIEs_tags_13)
		/sizeof(asn_DEF_E2N_GlobalGNB_ID_ExtIEs_tags_13[0]), /* 1 */
	asn_DEF_E2N_GlobalGNB_ID_ExtIEs_tags_13,	/* Same as above */
	sizeof(asn_DEF_E2N_GlobalGNB_ID_ExtIEs_tags_13)
		/sizeof(asn_DEF_E2N_GlobalGNB_ID_ExtIEs_tags_13[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2N_GlobalGNB_ID_ExtIEs_13,
	3,	/* Elements count */
	&asn_SPC_E2N_GlobalGNB_ID_ExtIEs_specs_13	/* Additional specs */
};

