/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/X2AP-minimized.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_Cause_H_
#define	_E2N_Cause_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E2N_CauseRadioNetwork.h"
#include "E2N_CauseTransport.h"
#include "E2N_CauseProtocol.h"
#include "E2N_CauseMisc.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2N_Cause_PR {
	E2N_Cause_PR_NOTHING,	/* No components present */
	E2N_Cause_PR_radioNetwork,
	E2N_Cause_PR_transport,
	E2N_Cause_PR_protocol,
	E2N_Cause_PR_misc
	/* Extensions may appear below */
	
} E2N_Cause_PR;

/* E2N_Cause */
typedef struct E2N_Cause {
	E2N_Cause_PR present;
	union E2N_Cause_u {
		E2N_CauseRadioNetwork_t	 radioNetwork;
		E2N_CauseTransport_t	 transport;
		E2N_CauseProtocol_t	 protocol;
		E2N_CauseMisc_t	 misc;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_Cause_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2N_Cause;

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_Cause_H_ */
#include <asn_internal.h>
