/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/X2AP-minimized.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_PLMN_Identity_H_
#define	_E2N_PLMN_Identity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E2N_PLMN-Identity */
typedef OCTET_STRING_t	 E2N_PLMN_Identity_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E2N_PLMN_Identity_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2N_PLMN_Identity;
asn_struct_free_f E2N_PLMN_Identity_free;
asn_struct_print_f E2N_PLMN_Identity_print;
asn_constr_check_f E2N_PLMN_Identity_constraint;
ber_type_decoder_f E2N_PLMN_Identity_decode_ber;
der_type_encoder_f E2N_PLMN_Identity_encode_der;
xer_type_decoder_f E2N_PLMN_Identity_decode_xer;
xer_type_encoder_f E2N_PLMN_Identity_encode_xer;
per_type_decoder_f E2N_PLMN_Identity_decode_uper;
per_type_encoder_f E2N_PLMN_Identity_encode_uper;
per_type_decoder_f E2N_PLMN_Identity_decode_aper;
per_type_encoder_f E2N_PLMN_Identity_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_PLMN_Identity_H_ */
#include <asn_internal.h>
