/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "../../asn_defs/asn1/e2ap-v031-subset.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_RANfunctionsIDcause_List_H_
#define	_E2N_RANfunctionsIDcause_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E2N_ProtocolIE_Single_Container;

/* E2N_RANfunctionsIDcause-List */
typedef struct E2N_RANfunctionsIDcause_List {
	A_SEQUENCE_OF(struct E2N_ProtocolIE_Single_Container) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_RANfunctionsIDcause_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2N_RANfunctionsIDcause_List;

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_RANfunctionsIDcause_List_H_ */
#include <asn_internal.h>
