/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-CommonDataTypes"
 * 	found in "../../asn_defs/asn1/X2AP-minimized.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_ProtocolIE_ID_H_
#define	_E2N_ProtocolIE_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E2N_ProtocolIE-ID */
typedef long	 E2N_ProtocolIE_ID_t;

/* Implementation */
#define E2N_ProtocolIE_ID_id_RANfunction_Item	((E2N_ProtocolIE_ID_t)60001)
#define E2N_ProtocolIE_ID_id_RANfunctionDefinition	((E2N_ProtocolIE_ID_t)60002)
#define E2N_ProtocolIE_ID_id_RANfunctionID	((E2N_ProtocolIE_ID_t)60003)
#define E2N_ProtocolIE_ID_id_RANfunctionID_Item	((E2N_ProtocolIE_ID_t)60004)
#define E2N_ProtocolIE_ID_id_RANfunctionIEcause_Item	((E2N_ProtocolIE_ID_t)60005)
#define E2N_ProtocolIE_ID_id_RANfunctionsAccepted	((E2N_ProtocolIE_ID_t)60006)
#define E2N_ProtocolIE_ID_id_RANfunctionsAdded	((E2N_ProtocolIE_ID_t)60007)
#define E2N_ProtocolIE_ID_id_RANfunctionsDeleted	((E2N_ProtocolIE_ID_t)60008)
#define E2N_ProtocolIE_ID_id_RANfunctionsModified	((E2N_ProtocolIE_ID_t)60009)
#define E2N_ProtocolIE_ID_id_RANfunctionsRejected	((E2N_ProtocolIE_ID_t)60010)
#define E2N_ProtocolIE_ID_id_RICaction_ToBeSetup_Item	((E2N_ProtocolIE_ID_t)60011)
#define E2N_ProtocolIE_ID_id_RICactions_Admitted	((E2N_ProtocolIE_ID_t)60012)
#define E2N_ProtocolIE_ID_id_RICaction_Admitted_Item	((E2N_ProtocolIE_ID_t)60013)
#define E2N_ProtocolIE_ID_id_RICactions_NotAdmitted	((E2N_ProtocolIE_ID_t)60014)
#define E2N_ProtocolIE_ID_id_RICaction_NotAdmitted_Item	((E2N_ProtocolIE_ID_t)60015)
#define E2N_ProtocolIE_ID_id_RICactionDefinition	((E2N_ProtocolIE_ID_t)60016)
#define E2N_ProtocolIE_ID_id_RICactionID	((E2N_ProtocolIE_ID_t)60017)
#define E2N_ProtocolIE_ID_id_RICactionType	((E2N_ProtocolIE_ID_t)60018)
#define E2N_ProtocolIE_ID_id_RICcallProcessID	((E2N_ProtocolIE_ID_t)60019)
#define E2N_ProtocolIE_ID_id_RICcause	((E2N_ProtocolIE_ID_t)60020)
#define E2N_ProtocolIE_ID_id_RICcontrolAckRequest	((E2N_ProtocolIE_ID_t)60021)
#define E2N_ProtocolIE_ID_id_RICcontrolHeader	((E2N_ProtocolIE_ID_t)60022)
#define E2N_ProtocolIE_ID_id_RICcontrolMessage	((E2N_ProtocolIE_ID_t)60023)
#define E2N_ProtocolIE_ID_id_RICcontrolStatus	((E2N_ProtocolIE_ID_t)60024)
#define E2N_ProtocolIE_ID_id_RICeventTriggerDefinition	((E2N_ProtocolIE_ID_t)60025)
#define E2N_ProtocolIE_ID_id_RICindicationHeader	((E2N_ProtocolIE_ID_t)60026)
#define E2N_ProtocolIE_ID_id_RICindicationMessage	((E2N_ProtocolIE_ID_t)60027)
#define E2N_ProtocolIE_ID_id_RICindicationSN	((E2N_ProtocolIE_ID_t)60028)
#define E2N_ProtocolIE_ID_id_RICindicationType	((E2N_ProtocolIE_ID_t)60029)
#define E2N_ProtocolIE_ID_id_RICrequestID	((E2N_ProtocolIE_ID_t)60030)
#define E2N_ProtocolIE_ID_id_RICrequestorID	((E2N_ProtocolIE_ID_t)60031)
#define E2N_ProtocolIE_ID_id_RICrequestSequenceNumber	((E2N_ProtocolIE_ID_t)60032)
#define E2N_ProtocolIE_ID_id_RICsubscription	((E2N_ProtocolIE_ID_t)60033)
#define E2N_ProtocolIE_ID_id_RICsubsequentAction	((E2N_ProtocolIE_ID_t)60034)
#define E2N_ProtocolIE_ID_id_RICsubsequentActionType	((E2N_ProtocolIE_ID_t)60035)
#define E2N_ProtocolIE_ID_id_RICtimeToWait	((E2N_ProtocolIE_ID_t)60036)
#define E2N_ProtocolIE_ID_id_CriticalityDiagnostics	((E2N_ProtocolIE_ID_t)17)
#define E2N_ProtocolIE_ID_id_GlobalENB_ID	((E2N_ProtocolIE_ID_t)21)
#define E2N_ProtocolIE_ID_id_TimeToWait	((E2N_ProtocolIE_ID_t)22)
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_ID;
asn_struct_free_f E2N_ProtocolIE_ID_free;
asn_struct_print_f E2N_ProtocolIE_ID_print;
asn_constr_check_f E2N_ProtocolIE_ID_constraint;
ber_type_decoder_f E2N_ProtocolIE_ID_decode_ber;
der_type_encoder_f E2N_ProtocolIE_ID_encode_der;
xer_type_decoder_f E2N_ProtocolIE_ID_decode_xer;
xer_type_encoder_f E2N_ProtocolIE_ID_encode_xer;
per_type_decoder_f E2N_ProtocolIE_ID_decode_uper;
per_type_encoder_f E2N_ProtocolIE_ID_encode_uper;
per_type_decoder_f E2N_ProtocolIE_ID_decode_aper;
per_type_encoder_f E2N_ProtocolIE_ID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_ProtocolIE_ID_H_ */
#include <asn_internal.h>
