/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-Containers"
 * 	found in "../../asn_defs/asn1/X2AP-minimized.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_ProtocolExtensionContainer_H_
#define	_E2N_ProtocolExtensionContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E2N_CriticalityDiagnostics_ExtIEs;
struct E2N_CriticalityDiagnostics_IE_List_ExtIEs;
struct E2N_GlobalENB_ID_ExtIEs;
struct E2N_GlobalGNB_ID_ExtIEs;

/* E2N_ProtocolExtensionContainer */
typedef struct E2N_ProtocolExtensionContainer_480P0 {
	A_SEQUENCE_OF(struct E2N_CriticalityDiagnostics_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolExtensionContainer_480P0_t;
typedef struct E2N_ProtocolExtensionContainer_480P1 {
	A_SEQUENCE_OF(struct E2N_CriticalityDiagnostics_IE_List_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolExtensionContainer_480P1_t;
typedef struct E2N_ProtocolExtensionContainer_480P2 {
	A_SEQUENCE_OF(struct E2N_GlobalENB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolExtensionContainer_480P2_t;
typedef struct E2N_ProtocolExtensionContainer_480P3 {
	A_SEQUENCE_OF(struct E2N_GlobalGNB_ID_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolExtensionContainer_480P3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolExtensionContainer_480P0;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolExtensionContainer_480P0_specs_1;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolExtensionContainer_480P0_1[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolExtensionContainer_480P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolExtensionContainer_480P1;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolExtensionContainer_480P1_specs_3;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolExtensionContainer_480P1_3[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolExtensionContainer_480P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolExtensionContainer_480P2;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolExtensionContainer_480P2_specs_5;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolExtensionContainer_480P2_5[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolExtensionContainer_480P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolExtensionContainer_480P3;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolExtensionContainer_480P3_specs_7;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolExtensionContainer_480P3_7[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolExtensionContainer_480P3_constr_7;

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_ProtocolExtensionContainer_H_ */
#include <asn_internal.h>
