/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-gNB-X2-IEs"
 * 	found in "../../asn_defs/asn1/e2sm-gNB-X2-release-1-v041.asn.txt"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_InterfaceProtocolIE_Value_H_
#define	_E2N_InterfaceProtocolIE_Value_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <BOOLEAN.h>
#include <BIT_STRING.h>
#include <OCTET_STRING.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2N_InterfaceProtocolIE_Value_PR {
	E2N_InterfaceProtocolIE_Value_PR_NOTHING,	/* No components present */
	E2N_InterfaceProtocolIE_Value_PR_valueInt,
	E2N_InterfaceProtocolIE_Value_PR_valueEnum,
	E2N_InterfaceProtocolIE_Value_PR_valueBool,
	E2N_InterfaceProtocolIE_Value_PR_valueBitS,
	E2N_InterfaceProtocolIE_Value_PR_valueOctS
	/* Extensions may appear below */
	
} E2N_InterfaceProtocolIE_Value_PR;

/* E2N_InterfaceProtocolIE-Value */
typedef struct E2N_InterfaceProtocolIE_Value {
	E2N_InterfaceProtocolIE_Value_PR present;
	union E2N_InterfaceProtocolIE_Value_u {
		long	 valueInt;
		long	 valueEnum;
		BOOLEAN_t	 valueBool;
		BIT_STRING_t	 valueBitS;
		OCTET_STRING_t	 valueOctS;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_InterfaceProtocolIE_Value_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2N_InterfaceProtocolIE_Value;
extern asn_CHOICE_specifics_t asn_SPC_E2N_InterfaceProtocolIE_Value_specs_1;
extern asn_TYPE_member_t asn_MBR_E2N_InterfaceProtocolIE_Value_1[5];
extern asn_per_constraints_t asn_PER_type_E2N_InterfaceProtocolIE_Value_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_InterfaceProtocolIE_Value_H_ */
#include <asn_internal.h>
