/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-Containers"
 * 	found in "../../asn_defs/asn1/X2AP-minimized.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#include "E2N_ProtocolExtensionContainer.h"

#include "E2N_ProtocolExtensionField.h"
asn_per_constraints_t asn_PER_type_E2N_ProtocolExtensionContainer_480P0_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2N_ProtocolExtensionContainer_480P1_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2N_ProtocolExtensionContainer_480P2_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_E2N_ProtocolExtensionContainer_480P3_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_E2N_ProtocolExtensionContainer_480P0_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2N_CriticalityDiagnostics_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2N_ProtocolExtensionContainer_480P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolExtensionContainer_480P0_specs_1 = {
	sizeof(struct E2N_ProtocolExtensionContainer_480P0),
	offsetof(struct E2N_ProtocolExtensionContainer_480P0, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolExtensionContainer_480P0 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2N_ProtocolExtensionContainer_480P0_tags_1,
	sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P0_tags_1)
		/sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P0_tags_1[0]), /* 1 */
	asn_DEF_E2N_ProtocolExtensionContainer_480P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P0_tags_1)
		/sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P0_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_E2N_ProtocolExtensionContainer_480P0_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_E2N_ProtocolExtensionContainer_480P0_1,
	1,	/* Single element */
	&asn_SPC_E2N_ProtocolExtensionContainer_480P0_specs_1	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2N_ProtocolExtensionContainer_480P1_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2N_CriticalityDiagnostics_IE_List_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2N_ProtocolExtensionContainer_480P1_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolExtensionContainer_480P1_specs_3 = {
	sizeof(struct E2N_ProtocolExtensionContainer_480P1),
	offsetof(struct E2N_ProtocolExtensionContainer_480P1, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolExtensionContainer_480P1 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2N_ProtocolExtensionContainer_480P1_tags_3,
	sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P1_tags_3)
		/sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P1_tags_3[0]), /* 1 */
	asn_DEF_E2N_ProtocolExtensionContainer_480P1_tags_3,	/* Same as above */
	sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P1_tags_3)
		/sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P1_tags_3[0]), /* 1 */
	{ 0, &asn_PER_type_E2N_ProtocolExtensionContainer_480P1_constr_3, SEQUENCE_OF_constraint },
	asn_MBR_E2N_ProtocolExtensionContainer_480P1_3,
	1,	/* Single element */
	&asn_SPC_E2N_ProtocolExtensionContainer_480P1_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2N_ProtocolExtensionContainer_480P2_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2N_GlobalENB_ID_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2N_ProtocolExtensionContainer_480P2_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolExtensionContainer_480P2_specs_5 = {
	sizeof(struct E2N_ProtocolExtensionContainer_480P2),
	offsetof(struct E2N_ProtocolExtensionContainer_480P2, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolExtensionContainer_480P2 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2N_ProtocolExtensionContainer_480P2_tags_5,
	sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P2_tags_5)
		/sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P2_tags_5[0]), /* 1 */
	asn_DEF_E2N_ProtocolExtensionContainer_480P2_tags_5,	/* Same as above */
	sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P2_tags_5)
		/sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P2_tags_5[0]), /* 1 */
	{ 0, &asn_PER_type_E2N_ProtocolExtensionContainer_480P2_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_E2N_ProtocolExtensionContainer_480P2_5,
	1,	/* Single element */
	&asn_SPC_E2N_ProtocolExtensionContainer_480P2_specs_5	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2N_ProtocolExtensionContainer_480P3_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_E2N_GlobalGNB_ID_ExtIEs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_E2N_ProtocolExtensionContainer_480P3_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolExtensionContainer_480P3_specs_7 = {
	sizeof(struct E2N_ProtocolExtensionContainer_480P3),
	offsetof(struct E2N_ProtocolExtensionContainer_480P3, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolExtensionContainer_480P3 = {
	"ProtocolExtensionContainer",
	"ProtocolExtensionContainer",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_E2N_ProtocolExtensionContainer_480P3_tags_7,
	sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P3_tags_7)
		/sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P3_tags_7[0]), /* 1 */
	asn_DEF_E2N_ProtocolExtensionContainer_480P3_tags_7,	/* Same as above */
	sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P3_tags_7)
		/sizeof(asn_DEF_E2N_ProtocolExtensionContainer_480P3_tags_7[0]), /* 1 */
	{ 0, &asn_PER_type_E2N_ProtocolExtensionContainer_480P3_constr_7, SEQUENCE_OF_constraint },
	asn_MBR_E2N_ProtocolExtensionContainer_480P3_7,
	1,	/* Single element */
	&asn_SPC_E2N_ProtocolExtensionContainer_480P3_specs_7	/* Additional specs */
};

