/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "E2AP-PDU-Contents"
 * 	found in "../../asn_defs/asn1/e2ap-v031-subset.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_RICaction_NotAdmitted_Item_H_
#define	_E2N_RICaction_NotAdmitted_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E2N_RICactionID.h"
#include "E2N_RICcause.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E2N_RICaction-NotAdmitted-Item */
typedef struct E2N_RICaction_NotAdmitted_Item {
	E2N_RICactionID_t	 ricActionID;
	E2N_RICcause_t	 ricCause;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_RICaction_NotAdmitted_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2N_RICaction_NotAdmitted_Item;

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_RICaction_NotAdmitted_Item_H_ */
#include <asn_internal.h>
