/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-Containers"
 * 	found in "../../asn_defs/asn1/X2AP-minimized.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_PrivateIE_Field_H_
#define	_E2N_PrivateIE_Field_H_


#include <asn_application.h>

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_PrivateIE_Field_H_ */
#include <asn_internal.h>
