/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-Containers"
 * 	found in "../../asn_defs/asn1/X2AP-minimized.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_ProtocolIE_Container_H_
#define	_E2N_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct E2N_RICsubscriptionRequest_IEs;
struct E2N_RICsubscriptionResponse_IEs;
struct E2N_RICsubscriptionFailure_IEs;
struct E2N_RICsubscriptionDeleteRequest_IEs;
struct E2N_RICsubscriptionDeleteResponse_IEs;
struct E2N_RICsubscriptionDeleteFailure_IEs;
struct E2N_RICindication_IEs;
struct E2N_RICcontrolRequest_IEs;
struct E2N_RICcontrolAcknowledge_IEs;
struct E2N_RICcontrolFailure_IEs;
struct E2N_RICserviceUpdate_IEs;
struct E2N_RICserviceUpdateAcknowledge_IEs;
struct E2N_RICserviceUpdateFailure_IEs;
struct E2N_RICserviceQuery_IEs;

/* E2N_ProtocolIE-Container */
typedef struct E2N_ProtocolIE_Container_429P0 {
	A_SEQUENCE_OF(struct E2N_RICsubscriptionRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P0_t;
typedef struct E2N_ProtocolIE_Container_429P1 {
	A_SEQUENCE_OF(struct E2N_RICsubscriptionResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P1_t;
typedef struct E2N_ProtocolIE_Container_429P2 {
	A_SEQUENCE_OF(struct E2N_RICsubscriptionFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P2_t;
typedef struct E2N_ProtocolIE_Container_429P3 {
	A_SEQUENCE_OF(struct E2N_RICsubscriptionDeleteRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P3_t;
typedef struct E2N_ProtocolIE_Container_429P4 {
	A_SEQUENCE_OF(struct E2N_RICsubscriptionDeleteResponse_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P4_t;
typedef struct E2N_ProtocolIE_Container_429P5 {
	A_SEQUENCE_OF(struct E2N_RICsubscriptionDeleteFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P5_t;
typedef struct E2N_ProtocolIE_Container_429P6 {
	A_SEQUENCE_OF(struct E2N_RICindication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P6_t;
typedef struct E2N_ProtocolIE_Container_429P7 {
	A_SEQUENCE_OF(struct E2N_RICcontrolRequest_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P7_t;
typedef struct E2N_ProtocolIE_Container_429P8 {
	A_SEQUENCE_OF(struct E2N_RICcontrolAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P8_t;
typedef struct E2N_ProtocolIE_Container_429P9 {
	A_SEQUENCE_OF(struct E2N_RICcontrolFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P9_t;
typedef struct E2N_ProtocolIE_Container_429P10 {
	A_SEQUENCE_OF(struct E2N_RICserviceUpdate_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P10_t;
typedef struct E2N_ProtocolIE_Container_429P11 {
	A_SEQUENCE_OF(struct E2N_RICserviceUpdateAcknowledge_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P11_t;
typedef struct E2N_ProtocolIE_Container_429P12 {
	A_SEQUENCE_OF(struct E2N_RICserviceUpdateFailure_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P12_t;
typedef struct E2N_ProtocolIE_Container_429P13 {
	A_SEQUENCE_OF(struct E2N_RICserviceQuery_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2N_ProtocolIE_Container_429P13_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P0;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P0_specs_1;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P0_1[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P1;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P1_specs_3;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P1_3[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P2;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P2_specs_5;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P2_5[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P3;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P3_specs_7;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P3_7[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P4;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P4_specs_9;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P4_9[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P5;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P5_specs_11;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P5_11[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P6;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P6_specs_13;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P6_13[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P7;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P7_specs_15;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P7_15[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P8;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P8_specs_17;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P8_17[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P9;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P9_specs_19;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P9_19[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P10;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P10_specs_21;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P10_21[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P11;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P11_specs_23;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P11_23[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P12;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P12_specs_25;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P12_25[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProtocolIE_Container_429P13;
extern asn_SET_OF_specifics_t asn_SPC_E2N_ProtocolIE_Container_429P13_specs_27;
extern asn_TYPE_member_t asn_MBR_E2N_ProtocolIE_Container_429P13_27[1];
extern asn_per_constraints_t asn_PER_type_E2N_ProtocolIE_Container_429P13_constr_27;

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_ProtocolIE_Container_H_ */
#include <asn_internal.h>
