/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/X2AP-minimized.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_CauseMisc_H_
#define	_E2N_CauseMisc_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum E2N_CauseMisc {
	E2N_CauseMisc_control_processing_overload	= 0,
	E2N_CauseMisc_hardware_failure	= 1,
	E2N_CauseMisc_om_intervention	= 2,
	E2N_CauseMisc_not_enough_user_plane_processing_resources	= 3,
	E2N_CauseMisc_unspecified	= 4
	/*
	 * Enumeration is extensible
	 */
} e_E2N_CauseMisc;

/* E2N_CauseMisc */
typedef long	 E2N_CauseMisc_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E2N_CauseMisc_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2N_CauseMisc;
extern const asn_INTEGER_specifics_t asn_SPC_CauseMisc_specs_1;
asn_struct_free_f CauseMisc_free;
asn_struct_print_f CauseMisc_print;
asn_constr_check_f CauseMisc_constraint;
ber_type_decoder_f CauseMisc_decode_ber;
der_type_encoder_f CauseMisc_encode_der;
xer_type_decoder_f CauseMisc_decode_xer;
xer_type_encoder_f CauseMisc_encode_xer;
per_type_decoder_f CauseMisc_decode_uper;
per_type_encoder_f CauseMisc_encode_uper;
per_type_decoder_f CauseMisc_decode_aper;
per_type_encoder_f CauseMisc_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_CauseMisc_H_ */
#include <asn_internal.h>
