/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-CommonDataTypes"
 * 	found in "../../asn_defs/asn1/X2AP-minimized.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_E2N_ProcedureCode_H_
#define	_E2N_ProcedureCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* E2N_ProcedureCode */
typedef long	 E2N_ProcedureCode_t;

/* Implementation */
#define E2N_ProcedureCode_id_ricSubscription	((E2N_ProcedureCode_t)201)
#define E2N_ProcedureCode_id_ricSubscriptionDelete	((E2N_ProcedureCode_t)202)
#define E2N_ProcedureCode_id_ricServiceUpdate	((E2N_ProcedureCode_t)203)
#define E2N_ProcedureCode_id_ricControl	((E2N_ProcedureCode_t)204)
#define E2N_ProcedureCode_id_ricIndication	((E2N_ProcedureCode_t)205)
#define E2N_ProcedureCode_id_ricServiceQuery	((E2N_ProcedureCode_t)206)
extern asn_per_constraints_t asn_PER_type_E2N_ProcedureCode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E2N_ProcedureCode;
asn_struct_free_f E2N_ProcedureCode_free;
asn_struct_print_f E2N_ProcedureCode_print;
asn_constr_check_f E2N_ProcedureCode_constraint;
ber_type_decoder_f E2N_ProcedureCode_decode_ber;
der_type_encoder_f E2N_ProcedureCode_encode_der;
xer_type_decoder_f E2N_ProcedureCode_decode_xer;
xer_type_encoder_f E2N_ProcedureCode_encode_xer;
per_type_decoder_f E2N_ProcedureCode_decode_uper;
per_type_encoder_f E2N_ProcedureCode_encode_uper;
per_type_decoder_f E2N_ProcedureCode_decode_aper;
per_type_encoder_f E2N_ProcedureCode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E2N_ProcedureCode_H_ */
#include <asn_internal.h>
