/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Descriptions"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#include "X2N_InitiatingMessage.h"

static const long asn_VAL_1_X2N_id_handoverPreparation = 0;
static const long asn_VAL_1_X2N_reject = 0;
static const long asn_VAL_2_X2N_id_reset = 7;
static const long asn_VAL_2_X2N_reject = 0;
static const long asn_VAL_3_X2N_id_x2Setup = 6;
static const long asn_VAL_3_X2N_reject = 0;
static const long asn_VAL_4_X2N_id_resourceStatusReportingInitiation = 9;
static const long asn_VAL_4_X2N_reject = 0;
static const long asn_VAL_5_X2N_id_eNBConfigurationUpdate = 8;
static const long asn_VAL_5_X2N_reject = 0;
static const long asn_VAL_6_X2N_id_mobilitySettingsChange = 12;
static const long asn_VAL_6_X2N_reject = 0;
static const long asn_VAL_7_X2N_id_cellActivation = 15;
static const long asn_VAL_7_X2N_reject = 0;
static const long asn_VAL_8_X2N_id_seNBAdditionPreparation = 19;
static const long asn_VAL_8_X2N_reject = 0;
static const long asn_VAL_9_X2N_id_meNBinitiatedSeNBModificationPreparation = 21;
static const long asn_VAL_9_X2N_reject = 0;
static const long asn_VAL_10_X2N_id_seNBinitiatedSeNBModification = 22;
static const long asn_VAL_10_X2N_reject = 0;
static const long asn_VAL_11_X2N_id_seNBinitiatedSeNBRelease = 24;
static const long asn_VAL_11_X2N_reject = 0;
static const long asn_VAL_12_X2N_id_x2Removal = 18;
static const long asn_VAL_12_X2N_reject = 0;
static const long asn_VAL_13_X2N_id_retrieveUEContext = 26;
static const long asn_VAL_13_X2N_reject = 0;
static const long asn_VAL_14_X2N_id_sgNBAdditionPreparation = 27;
static const long asn_VAL_14_X2N_reject = 0;
static const long asn_VAL_15_X2N_id_meNBinitiatedSgNBModificationPreparation = 29;
static const long asn_VAL_15_X2N_reject = 0;
static const long asn_VAL_16_X2N_id_sgNBinitiatedSgNBModification = 30;
static const long asn_VAL_16_X2N_reject = 0;
static const long asn_VAL_17_X2N_id_meNBinitiatedSgNBRelease = 31;
static const long asn_VAL_17_X2N_ignore = 1;
static const long asn_VAL_18_X2N_id_sgNBinitiatedSgNBRelease = 32;
static const long asn_VAL_18_X2N_reject = 0;
static const long asn_VAL_19_X2N_id_sgNBChange = 34;
static const long asn_VAL_19_X2N_reject = 0;
static const long asn_VAL_20_X2N_id_endcX2Setup = 36;
static const long asn_VAL_20_X2N_reject = 0;
static const long asn_VAL_21_X2N_id_endcConfigurationUpdate = 37;
static const long asn_VAL_21_X2N_reject = 0;
static const long asn_VAL_22_X2N_id_endcCellActivation = 39;
static const long asn_VAL_22_X2N_reject = 0;
static const long asn_VAL_23_X2N_id_endcPartialReset = 40;
static const long asn_VAL_23_X2N_reject = 0;
static const long asn_VAL_24_X2N_id_eUTRANRCellResourceCoordination = 41;
static const long asn_VAL_24_X2N_reject = 0;
static const long asn_VAL_25_X2N_id_endcX2Removal = 43;
static const long asn_VAL_25_X2N_reject = 0;
static const long asn_VAL_26_X2N_id_snStatusTransfer = 4;
static const long asn_VAL_26_X2N_ignore = 1;
static const long asn_VAL_27_X2N_id_uEContextRelease = 5;
static const long asn_VAL_27_X2N_ignore = 1;
static const long asn_VAL_28_X2N_id_handoverCancel = 1;
static const long asn_VAL_28_X2N_ignore = 1;
static const long asn_VAL_29_X2N_id_errorIndication = 3;
static const long asn_VAL_29_X2N_ignore = 1;
static const long asn_VAL_30_X2N_id_resourceStatusReporting = 10;
static const long asn_VAL_30_X2N_ignore = 1;
static const long asn_VAL_31_X2N_id_loadIndication = 2;
static const long asn_VAL_31_X2N_ignore = 1;
static const long asn_VAL_32_X2N_id_privateMessage = 11;
static const long asn_VAL_32_X2N_ignore = 1;
static const long asn_VAL_33_X2N_id_rLFIndication = 13;
static const long asn_VAL_33_X2N_ignore = 1;
static const long asn_VAL_34_X2N_id_handoverReport = 14;
static const long asn_VAL_34_X2N_ignore = 1;
static const long asn_VAL_35_X2N_id_x2Release = 16;
static const long asn_VAL_35_X2N_reject = 0;
static const long asn_VAL_36_X2N_id_x2APMessageTransfer = 17;
static const long asn_VAL_36_X2N_reject = 0;
static const long asn_VAL_37_X2N_id_seNBReconfigurationCompletion = 20;
static const long asn_VAL_37_X2N_ignore = 1;
static const long asn_VAL_38_X2N_id_meNBinitiatedSeNBRelease = 23;
static const long asn_VAL_38_X2N_ignore = 1;
static const long asn_VAL_39_X2N_id_seNBCounterCheck = 25;
static const long asn_VAL_39_X2N_reject = 0;
static const long asn_VAL_40_X2N_id_sgNBReconfigurationCompletion = 28;
static const long asn_VAL_40_X2N_ignore = 1;
static const long asn_VAL_41_X2N_id_sgNBCounterCheck = 33;
static const long asn_VAL_41_X2N_reject = 0;
static const long asn_VAL_42_X2N_id_rRCTransfer = 35;
static const long asn_VAL_42_X2N_reject = 0;
static const long asn_VAL_43_X2N_id_secondaryRATDataUsageReport = 38;
static const long asn_VAL_43_X2N_reject = 0;
static const long asn_VAL_44_X2N_id_SgNBActivityNotification = 42;
static const long asn_VAL_44_X2N_reject = 0;
static const long asn_VAL_45_X2N_id_dataForwardingAddressIndication = 44;
static const long asn_VAL_45_X2N_ignore = 1;
static const long asn_VAL_46_X2N_id_gNBStatusIndication = 45;
static const long asn_VAL_46_X2N_ignore = 1;
static const asn_ioc_cell_t asn_IOS_X2N_X2AP_ELEMENTARY_PROCEDURES_1_rows[] = {
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_HandoverRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_HandoverRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_HandoverPreparationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_1_X2N_id_handoverPreparation },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_1_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_ResetRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_ResetResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_2_X2N_id_reset },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_2_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_X2SetupRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_X2SetupResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_X2SetupFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_3_X2N_id_x2Setup },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_3_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_ResourceStatusRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_ResourceStatusResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_ResourceStatusFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_4_X2N_id_resourceStatusReportingInitiation },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_4_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_ENBConfigurationUpdate },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_ENBConfigurationUpdateAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_ENBConfigurationUpdateFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_5_X2N_id_eNBConfigurationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_5_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_MobilityChangeRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_MobilityChangeAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_MobilityChangeFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_6_X2N_id_mobilitySettingsChange },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_6_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_CellActivationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_CellActivationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_CellActivationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_7_X2N_id_cellActivation },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_7_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SeNBAdditionRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_SeNBAdditionRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_SeNBAdditionRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_8_X2N_id_seNBAdditionPreparation },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_8_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SeNBModificationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_SeNBModificationRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_SeNBModificationRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_9_X2N_id_meNBinitiatedSeNBModificationPreparation },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_9_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SeNBModificationRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_SeNBModificationConfirm },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_SeNBModificationRefuse },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_10_X2N_id_seNBinitiatedSeNBModification },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_10_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SeNBReleaseRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_SeNBReleaseConfirm },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_11_X2N_id_seNBinitiatedSeNBRelease },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_11_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_X2RemovalRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_X2RemovalResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_X2RemovalFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_12_X2N_id_x2Removal },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_12_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_RetrieveUEContextRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_RetrieveUEContextResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_RetrieveUEContextFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_13_X2N_id_retrieveUEContext },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_13_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SgNBAdditionRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_SgNBAdditionRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_SgNBAdditionRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_14_X2N_id_sgNBAdditionPreparation },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_14_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SgNBModificationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_SgNBModificationRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_SgNBModificationRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_15_X2N_id_meNBinitiatedSgNBModificationPreparation },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_15_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SgNBModificationRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_SgNBModificationConfirm },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_SgNBModificationRefuse },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_16_X2N_id_sgNBinitiatedSgNBModification },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_16_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SgNBReleaseRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_SgNBReleaseRequestAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_SgNBReleaseRequestReject },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_17_X2N_id_meNBinitiatedSgNBRelease },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_17_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SgNBReleaseRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_SgNBReleaseConfirm },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_18_X2N_id_sgNBinitiatedSgNBRelease },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_18_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SgNBChangeRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_SgNBChangeConfirm },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_SgNBChangeRefuse },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_19_X2N_id_sgNBChange },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_19_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_ENDCX2SetupRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_ENDCX2SetupResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_ENDCX2SetupFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_20_X2N_id_endcX2Setup },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_20_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_ENDCConfigurationUpdate },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_ENDCConfigurationUpdateAcknowledge },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_ENDCConfigurationUpdateFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_21_X2N_id_endcConfigurationUpdate },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_21_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_ENDCCellActivationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_ENDCCellActivationResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_ENDCCellActivationFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_22_X2N_id_endcCellActivation },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_22_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_ENDCPartialResetRequired },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_ENDCPartialResetConfirm },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_23_X2N_id_endcPartialReset },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_23_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_EUTRANRCellResourceCoordinationRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_EUTRANRCellResourceCoordinationResponse },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_24_X2N_id_eUTRANRCellResourceCoordination },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_24_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_ENDCX2RemovalRequest },
	{ "&SuccessfulOutcome", aioc__type, &asn_DEF_X2N_ENDCX2RemovalResponse },
	{ "&UnsuccessfulOutcome", aioc__type, &asn_DEF_X2N_ENDCX2RemovalFailure },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_25_X2N_id_endcX2Removal },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_25_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SNStatusTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_26_X2N_id_snStatusTransfer },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_26_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_UEContextRelease },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_27_X2N_id_uEContextRelease },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_27_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_HandoverCancel },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_28_X2N_id_handoverCancel },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_28_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_ErrorIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_29_X2N_id_errorIndication },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_29_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_ResourceStatusUpdate },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_30_X2N_id_resourceStatusReporting },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_30_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_LoadInformation },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_31_X2N_id_loadIndication },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_31_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_PrivateMessage },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_32_X2N_id_privateMessage },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_32_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_RLFIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_33_X2N_id_rLFIndication },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_33_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_HandoverReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_34_X2N_id_handoverReport },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_34_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_X2Release },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_35_X2N_id_x2Release },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_35_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_X2APMessageTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_36_X2N_id_x2APMessageTransfer },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_36_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SeNBReconfigurationComplete },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_37_X2N_id_seNBReconfigurationCompletion },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_37_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SeNBReleaseRequest },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_38_X2N_id_meNBinitiatedSeNBRelease },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_38_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SeNBCounterCheckRequest },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_39_X2N_id_seNBCounterCheck },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_39_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SgNBReconfigurationComplete },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_40_X2N_id_sgNBReconfigurationCompletion },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_40_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SgNBCounterCheckRequest },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_41_X2N_id_sgNBCounterCheck },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_41_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_RRCTransfer },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_42_X2N_id_rRCTransfer },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_42_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SecondaryRATDataUsageReport },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_43_X2N_id_secondaryRATDataUsageReport },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_43_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_SgNBActivityNotification },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_44_X2N_id_SgNBActivityNotification },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_44_X2N_reject },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_DataForwardingAddressIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_45_X2N_id_dataForwardingAddressIndication },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_45_X2N_ignore },
	{ "&InitiatingMessage", aioc__type, &asn_DEF_X2N_GNBStatusIndication },
	{ "&SuccessfulOutcome",  },
	{ "&UnsuccessfulOutcome",  },
	{ "&procedureCode", aioc__value, &asn_DEF_X2N_ProcedureCode, &asn_VAL_46_X2N_id_gNBStatusIndication },
	{ "&criticality", aioc__value, &asn_DEF_X2N_Criticality, &asn_VAL_46_X2N_ignore }
};
static const asn_ioc_set_t asn_IOS_X2N_X2AP_ELEMENTARY_PROCEDURES_1[] = {
	{ 46, 5, asn_IOS_X2N_X2AP_ELEMENTARY_PROCEDURES_1_rows }
};
static int
memb_X2N_procedureCode_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 255)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_type_selector_result_t
select_InitiatingMessage_X2N_criticality_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_X2N_X2AP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 4; /* &criticality */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct X2N_InitiatingMessage, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_X2N_criticality_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_type_selector_result_t
select_InitiatingMessage_X2N_value_type(const asn_TYPE_descriptor_t *parent_type, const void *parent_sptr) {
	asn_type_selector_result_t result = {0, 0};
	const asn_ioc_set_t *itable = asn_IOS_X2N_X2AP_ELEMENTARY_PROCEDURES_1;
	size_t constraining_column = 3; /* &procedureCode */
	size_t for_column = 0; /* &InitiatingMessage */
	size_t row, presence_index = 0;
	const long *constraining_value = (const long *)((const char *)parent_sptr + offsetof(struct X2N_InitiatingMessage, procedureCode));
	
	for(row=0; row < itable->rows_count; row++) {
	    const asn_ioc_cell_t *constraining_cell = &itable->rows[row * itable->columns_count + constraining_column];
	    const asn_ioc_cell_t *type_cell = &itable->rows[row * itable->columns_count + for_column];
	
	    if(type_cell->cell_kind == aioc__undefined)
	        continue;
	
	    presence_index++;
	    if(constraining_cell->type_descriptor->op->compare_struct(constraining_cell->type_descriptor, constraining_value, constraining_cell->value_sptr) == 0) {
	        result.type_descriptor = type_cell->type_descriptor;
	        result.presence_index = presence_index;
	        break;
	    }
	}
	
	return result;
}

static int
memb_X2N_value_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

static asn_per_constraints_t asn_PER_memb_X2N_procedureCode_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 8,  8,  0,  255 }	/* (0..255) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_X2N_criticality_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_X2N_value_constr_4 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_X2N_value_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.HandoverRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_HandoverRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"HandoverRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.ResetRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_ResetRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ResetRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.X2SetupRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_X2SetupRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"X2SetupRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.ResourceStatusRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_ResourceStatusRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ResourceStatusRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.ENBConfigurationUpdate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_ENBConfigurationUpdate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ENBConfigurationUpdate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.MobilityChangeRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_MobilityChangeRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"MobilityChangeRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.CellActivationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_CellActivationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"CellActivationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SeNBAdditionRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SeNBAdditionRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SeNBAdditionRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SeNBModificationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SeNBModificationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SeNBModificationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SeNBModificationRequired),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SeNBModificationRequired,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SeNBModificationRequired"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SeNBReleaseRequired),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SeNBReleaseRequired,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SeNBReleaseRequired"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.X2RemovalRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_X2RemovalRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"X2RemovalRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.RetrieveUEContextRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_RetrieveUEContextRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RetrieveUEContextRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SgNBAdditionRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SgNBAdditionRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBAdditionRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SgNBModificationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SgNBModificationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBModificationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SgNBModificationRequired),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SgNBModificationRequired,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBModificationRequired"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SgNBReleaseRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SgNBReleaseRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBReleaseRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SgNBReleaseRequired),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SgNBReleaseRequired,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBReleaseRequired"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SgNBChangeRequired),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SgNBChangeRequired,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBChangeRequired"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.ENDCX2SetupRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_ENDCX2SetupRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ENDCX2SetupRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.ENDCConfigurationUpdate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_ENDCConfigurationUpdate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ENDCConfigurationUpdate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.ENDCCellActivationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_ENDCCellActivationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ENDCCellActivationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.ENDCPartialResetRequired),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_ENDCPartialResetRequired,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ENDCPartialResetRequired"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.EUTRANRCellResourceCoordinationRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_EUTRANRCellResourceCoordinationRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"EUTRANRCellResourceCoordinationRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.ENDCX2RemovalRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_ENDCX2RemovalRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ENDCX2RemovalRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SNStatusTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SNStatusTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SNStatusTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.UEContextRelease),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_UEContextRelease,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"UEContextRelease"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.HandoverCancel),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_HandoverCancel,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"HandoverCancel"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.ErrorIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_ErrorIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ErrorIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.ResourceStatusUpdate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_ResourceStatusUpdate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ResourceStatusUpdate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.LoadInformation),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_LoadInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"LoadInformation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.PrivateMessage),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_PrivateMessage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"PrivateMessage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.RLFIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_RLFIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RLFIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.HandoverReport),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_HandoverReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"HandoverReport"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.X2Release),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_X2Release,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"X2Release"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.X2APMessageTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_X2APMessageTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"X2APMessageTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SeNBReconfigurationComplete),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SeNBReconfigurationComplete,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SeNBReconfigurationComplete"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SeNBReleaseRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SeNBReleaseRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SeNBReleaseRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SeNBCounterCheckRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SeNBCounterCheckRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SeNBCounterCheckRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SgNBReconfigurationComplete),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SgNBReconfigurationComplete,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBReconfigurationComplete"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SgNBCounterCheckRequest),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SgNBCounterCheckRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBCounterCheckRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.RRCTransfer),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_RRCTransfer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"RRCTransfer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SecondaryRATDataUsageReport),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SecondaryRATDataUsageReport,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SecondaryRATDataUsageReport"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.SgNBActivityNotification),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_SgNBActivityNotification,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"SgNBActivityNotification"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.DataForwardingAddressIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_DataForwardingAddressIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"DataForwardingAddressIndication"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage__value, choice.GNBStatusIndication),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_GNBStatusIndication,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"GNBStatusIndication"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_X2N_value_tag2el_4[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 45 }, /* HandoverRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, -1, 44 }, /* ResetRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, -2, 43 }, /* X2SetupRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -3, 42 }, /* ResourceStatusRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -4, 41 }, /* ENBConfigurationUpdate */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 5, -5, 40 }, /* MobilityChangeRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 6, -6, 39 }, /* CellActivationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 7, -7, 38 }, /* SeNBAdditionRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 8, -8, 37 }, /* SeNBModificationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 9, -9, 36 }, /* SeNBModificationRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 10, -10, 35 }, /* SeNBReleaseRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 11, -11, 34 }, /* X2RemovalRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 12, -12, 33 }, /* RetrieveUEContextRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 13, -13, 32 }, /* SgNBAdditionRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 14, -14, 31 }, /* SgNBModificationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 15, -15, 30 }, /* SgNBModificationRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 16, -16, 29 }, /* SgNBReleaseRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 17, -17, 28 }, /* SgNBReleaseRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 18, -18, 27 }, /* SgNBChangeRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 19, -19, 26 }, /* ENDCX2SetupRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 20, -20, 25 }, /* ENDCConfigurationUpdate */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 21, -21, 24 }, /* ENDCCellActivationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 22, -22, 23 }, /* ENDCPartialResetRequired */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 23, -23, 22 }, /* EUTRANRCellResourceCoordinationRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 24, -24, 21 }, /* ENDCX2RemovalRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 25, -25, 20 }, /* SNStatusTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 26, -26, 19 }, /* UEContextRelease */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 27, -27, 18 }, /* HandoverCancel */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 28, -28, 17 }, /* ErrorIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 29, -29, 16 }, /* ResourceStatusUpdate */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 30, -30, 15 }, /* LoadInformation */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 31, -31, 14 }, /* PrivateMessage */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 32, -32, 13 }, /* RLFIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 33, -33, 12 }, /* HandoverReport */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 34, -34, 11 }, /* X2Release */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 35, -35, 10 }, /* X2APMessageTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 36, -36, 9 }, /* SeNBReconfigurationComplete */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 37, -37, 8 }, /* SeNBReleaseRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 38, -38, 7 }, /* SeNBCounterCheckRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 39, -39, 6 }, /* SgNBReconfigurationComplete */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 40, -40, 5 }, /* SgNBCounterCheckRequest */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 41, -41, 4 }, /* RRCTransfer */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 42, -42, 3 }, /* SecondaryRATDataUsageReport */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 43, -43, 2 }, /* SgNBActivityNotification */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 44, -44, 1 }, /* DataForwardingAddressIndication */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 45, -45, 0 } /* GNBStatusIndication */
};
static asn_CHOICE_specifics_t asn_SPC_X2N_value_specs_4 = {
	sizeof(struct X2N_InitiatingMessage__value),
	offsetof(struct X2N_InitiatingMessage__value, _asn_ctx),
	offsetof(struct X2N_InitiatingMessage__value, present),
	sizeof(((struct X2N_InitiatingMessage__value *)0)->present),
	asn_MAP_X2N_value_tag2el_4,
	46,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_X2N_value_4 = {
	"value",
	"value",
	&asn_OP_OPEN_TYPE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, OPEN_TYPE_constraint },
	asn_MBR_X2N_value_4,
	46,	/* Elements count */
	&asn_SPC_X2N_value_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_X2N_InitiatingMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage, procedureCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_X2N_ProcedureCode,
		0,
		{ 0, &asn_PER_memb_X2N_procedureCode_constr_2,  memb_X2N_procedureCode_constraint_1 },
		0, 0, /* No default value */
		"procedureCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage, criticality),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_X2N_Criticality,
		select_InitiatingMessage_X2N_criticality_type,
		{ 0, &asn_PER_memb_X2N_criticality_constr_3,  memb_X2N_criticality_constraint_1 },
		0, 0, /* No default value */
		"criticality"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct X2N_InitiatingMessage, value),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_X2N_value_4,
		select_InitiatingMessage_X2N_value_type,
		{ 0, &asn_PER_memb_X2N_value_constr_4,  memb_X2N_value_constraint_1 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_X2N_InitiatingMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_X2N_InitiatingMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* procedureCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* criticality */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_X2N_InitiatingMessage_specs_1 = {
	sizeof(struct X2N_InitiatingMessage),
	offsetof(struct X2N_InitiatingMessage, _asn_ctx),
	asn_MAP_X2N_InitiatingMessage_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_X2N_InitiatingMessage = {
	"InitiatingMessage",
	"InitiatingMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_InitiatingMessage_tags_1,
	sizeof(asn_DEF_X2N_InitiatingMessage_tags_1)
		/sizeof(asn_DEF_X2N_InitiatingMessage_tags_1[0]), /* 1 */
	asn_DEF_X2N_InitiatingMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_X2N_InitiatingMessage_tags_1)
		/sizeof(asn_DEF_X2N_InitiatingMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_InitiatingMessage_1,
	3,	/* Elements count */
	&asn_SPC_X2N_InitiatingMessage_specs_1	/* Additional specs */
};

