/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_X2N_CNTypeRestrictionsItem_H_
#define	_X2N_CNTypeRestrictionsItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include "X2N_PLMN-Identity.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum X2N_CNTypeRestrictionsItem__cn_type {
	X2N_CNTypeRestrictionsItem__cn_type_fiveGC_forbidden	= 0
	/*
	 * Enumeration is extensible
	 */
} e_X2N_CNTypeRestrictionsItem__cn_type;

/* Forward declarations */
struct X2N_ProtocolExtensionContainer;

/* X2N_CNTypeRestrictionsItem */
typedef struct X2N_CNTypeRestrictionsItem {
	X2N_PLMN_Identity_t	 plmn_Id;
	long	 cn_type;
	struct X2N_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} X2N_CNTypeRestrictionsItem_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_X2N_cn_type_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_X2N_CNTypeRestrictionsItem;
extern asn_SEQUENCE_specifics_t asn_SPC_X2N_CNTypeRestrictionsItem_specs_1;
extern asn_TYPE_member_t asn_MBR_X2N_CNTypeRestrictionsItem_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _X2N_CNTypeRestrictionsItem_H_ */
#include <asn_internal.h>
