/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_X2N_SharedResourceType_H_
#define	_X2N_SharedResourceType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum X2N_SharedResourceType_PR {
	X2N_SharedResourceType_PR_NOTHING,	/* No components present */
	X2N_SharedResourceType_PR_uLOnlySharing,
	X2N_SharedResourceType_PR_uLandDLSharing
	/* Extensions may appear below */
	
} X2N_SharedResourceType_PR;

/* Forward declarations */
struct X2N_ULOnlySharing;
struct X2N_ULandDLSharing;

/* X2N_SharedResourceType */
typedef struct X2N_SharedResourceType {
	X2N_SharedResourceType_PR present;
	union X2N_SharedResourceType_u {
		struct X2N_ULOnlySharing	*uLOnlySharing;
		struct X2N_ULandDLSharing	*uLandDLSharing;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} X2N_SharedResourceType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2N_SharedResourceType;
extern asn_CHOICE_specifics_t asn_SPC_X2N_SharedResourceType_specs_1;
extern asn_TYPE_member_t asn_MBR_X2N_SharedResourceType_1[2];
extern asn_per_constraints_t asn_PER_type_X2N_SharedResourceType_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _X2N_SharedResourceType_H_ */
#include <asn_internal.h>
