/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#include "X2N_SgNBtoMeNBContainer.h"

/*
 * This type is implemented using OCTET_STRING,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_X2N_SgNBtoMeNBContainer_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (4 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_SgNBtoMeNBContainer = {
	"SgNBtoMeNBContainer",
	"SgNBtoMeNBContainer",
	&asn_OP_OCTET_STRING,
	asn_DEF_X2N_SgNBtoMeNBContainer_tags_1,
	sizeof(asn_DEF_X2N_SgNBtoMeNBContainer_tags_1)
		/sizeof(asn_DEF_X2N_SgNBtoMeNBContainer_tags_1[0]), /* 1 */
	asn_DEF_X2N_SgNBtoMeNBContainer_tags_1,	/* Same as above */
	sizeof(asn_DEF_X2N_SgNBtoMeNBContainer_tags_1)
		/sizeof(asn_DEF_X2N_SgNBtoMeNBContainer_tags_1[0]), /* 1 */
	{ 0, 0, OCTET_STRING_constraint },
	0, 0,	/* No members */
	&asn_SPC_OCTET_STRING_specs	/* Additional specs */
};

