/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Descriptions"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_X2N_InitiatingMessage_H_
#define	_X2N_InitiatingMessage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "X2N_ProcedureCode.h"
#include "X2N_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "X2N_HandoverRequest.h"
#include "X2N_HandoverRequestAcknowledge.h"
#include "X2N_HandoverPreparationFailure.h"
#include "X2N_ResetRequest.h"
#include "X2N_ResetResponse.h"
#include "X2N_X2SetupRequest.h"
#include "X2N_X2SetupResponse.h"
#include "X2N_X2SetupFailure.h"
#include "X2N_ResourceStatusRequest.h"
#include "X2N_ResourceStatusResponse.h"
#include "X2N_ResourceStatusFailure.h"
#include "X2N_ENBConfigurationUpdate.h"
#include "X2N_ENBConfigurationUpdateAcknowledge.h"
#include "X2N_ENBConfigurationUpdateFailure.h"
#include "X2N_MobilityChangeRequest.h"
#include "X2N_MobilityChangeAcknowledge.h"
#include "X2N_MobilityChangeFailure.h"
#include "X2N_CellActivationRequest.h"
#include "X2N_CellActivationResponse.h"
#include "X2N_CellActivationFailure.h"
#include "X2N_SeNBAdditionRequest.h"
#include "X2N_SeNBAdditionRequestAcknowledge.h"
#include "X2N_SeNBAdditionRequestReject.h"
#include "X2N_SeNBModificationRequest.h"
#include "X2N_SeNBModificationRequestAcknowledge.h"
#include "X2N_SeNBModificationRequestReject.h"
#include "X2N_SeNBModificationRequired.h"
#include "X2N_SeNBModificationConfirm.h"
#include "X2N_SeNBModificationRefuse.h"
#include "X2N_SeNBReleaseRequired.h"
#include "X2N_SeNBReleaseConfirm.h"
#include "X2N_X2RemovalRequest.h"
#include "X2N_X2RemovalResponse.h"
#include "X2N_X2RemovalFailure.h"
#include "X2N_RetrieveUEContextRequest.h"
#include "X2N_RetrieveUEContextResponse.h"
#include "X2N_RetrieveUEContextFailure.h"
#include "X2N_SgNBAdditionRequest.h"
#include "X2N_SgNBAdditionRequestAcknowledge.h"
#include "X2N_SgNBAdditionRequestReject.h"
#include "X2N_SgNBModificationRequest.h"
#include "X2N_SgNBModificationRequestAcknowledge.h"
#include "X2N_SgNBModificationRequestReject.h"
#include "X2N_SgNBModificationRequired.h"
#include "X2N_SgNBModificationConfirm.h"
#include "X2N_SgNBModificationRefuse.h"
#include "X2N_SgNBReleaseRequest.h"
#include "X2N_SgNBReleaseRequestAcknowledge.h"
#include "X2N_SgNBReleaseRequestReject.h"
#include "X2N_SgNBReleaseRequired.h"
#include "X2N_SgNBReleaseConfirm.h"
#include "X2N_SgNBChangeRequired.h"
#include "X2N_SgNBChangeConfirm.h"
#include "X2N_SgNBChangeRefuse.h"
#include "X2N_ENDCX2SetupRequest.h"
#include "X2N_ENDCX2SetupResponse.h"
#include "X2N_ENDCX2SetupFailure.h"
#include "X2N_ENDCConfigurationUpdate.h"
#include "X2N_ENDCConfigurationUpdateAcknowledge.h"
#include "X2N_ENDCConfigurationUpdateFailure.h"
#include "X2N_ENDCCellActivationRequest.h"
#include "X2N_ENDCCellActivationResponse.h"
#include "X2N_ENDCCellActivationFailure.h"
#include "X2N_ENDCPartialResetRequired.h"
#include "X2N_ENDCPartialResetConfirm.h"
#include "X2N_EUTRANRCellResourceCoordinationRequest.h"
#include "X2N_EUTRANRCellResourceCoordinationResponse.h"
#include "X2N_ENDCX2RemovalRequest.h"
#include "X2N_ENDCX2RemovalResponse.h"
#include "X2N_ENDCX2RemovalFailure.h"
#include "X2N_SNStatusTransfer.h"
#include "X2N_UEContextRelease.h"
#include "X2N_HandoverCancel.h"
#include "X2N_ErrorIndication.h"
#include "X2N_ResourceStatusUpdate.h"
#include "X2N_LoadInformation.h"
#include "X2N_PrivateMessage.h"
#include "X2N_RLFIndication.h"
#include "X2N_HandoverReport.h"
#include "X2N_X2Release.h"
#include "X2N_X2APMessageTransfer.h"
#include "X2N_SeNBReconfigurationComplete.h"
#include "X2N_SeNBReleaseRequest.h"
#include "X2N_SeNBCounterCheckRequest.h"
#include "X2N_SgNBReconfigurationComplete.h"
#include "X2N_SgNBCounterCheckRequest.h"
#include "X2N_RRCTransfer.h"
#include "X2N_SecondaryRATDataUsageReport.h"
#include "X2N_SgNBActivityNotification.h"
#include "X2N_DataForwardingAddressIndication.h"
#include "X2N_GNBStatusIndication.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum X2N_InitiatingMessage__value_PR {
	X2N_InitiatingMessage__value_PR_NOTHING,	/* No components present */
	X2N_InitiatingMessage__value_PR_HandoverRequest,
	X2N_InitiatingMessage__value_PR_ResetRequest,
	X2N_InitiatingMessage__value_PR_X2SetupRequest,
	X2N_InitiatingMessage__value_PR_ResourceStatusRequest,
	X2N_InitiatingMessage__value_PR_ENBConfigurationUpdate,
	X2N_InitiatingMessage__value_PR_MobilityChangeRequest,
	X2N_InitiatingMessage__value_PR_CellActivationRequest,
	X2N_InitiatingMessage__value_PR_SeNBAdditionRequest,
	X2N_InitiatingMessage__value_PR_SeNBModificationRequest,
	X2N_InitiatingMessage__value_PR_SeNBModificationRequired,
	X2N_InitiatingMessage__value_PR_SeNBReleaseRequired,
	X2N_InitiatingMessage__value_PR_X2RemovalRequest,
	X2N_InitiatingMessage__value_PR_RetrieveUEContextRequest,
	X2N_InitiatingMessage__value_PR_SgNBAdditionRequest,
	X2N_InitiatingMessage__value_PR_SgNBModificationRequest,
	X2N_InitiatingMessage__value_PR_SgNBModificationRequired,
	X2N_InitiatingMessage__value_PR_SgNBReleaseRequest,
	X2N_InitiatingMessage__value_PR_SgNBReleaseRequired,
	X2N_InitiatingMessage__value_PR_SgNBChangeRequired,
	X2N_InitiatingMessage__value_PR_ENDCX2SetupRequest,
	X2N_InitiatingMessage__value_PR_ENDCConfigurationUpdate,
	X2N_InitiatingMessage__value_PR_ENDCCellActivationRequest,
	X2N_InitiatingMessage__value_PR_ENDCPartialResetRequired,
	X2N_InitiatingMessage__value_PR_EUTRANRCellResourceCoordinationRequest,
	X2N_InitiatingMessage__value_PR_ENDCX2RemovalRequest,
	X2N_InitiatingMessage__value_PR_SNStatusTransfer,
	X2N_InitiatingMessage__value_PR_UEContextRelease,
	X2N_InitiatingMessage__value_PR_HandoverCancel,
	X2N_InitiatingMessage__value_PR_ErrorIndication,
	X2N_InitiatingMessage__value_PR_ResourceStatusUpdate,
	X2N_InitiatingMessage__value_PR_LoadInformation,
	X2N_InitiatingMessage__value_PR_PrivateMessage,
	X2N_InitiatingMessage__value_PR_RLFIndication,
	X2N_InitiatingMessage__value_PR_HandoverReport,
	X2N_InitiatingMessage__value_PR_X2Release,
	X2N_InitiatingMessage__value_PR_X2APMessageTransfer,
	X2N_InitiatingMessage__value_PR_SeNBReconfigurationComplete,
	X2N_InitiatingMessage__value_PR_SeNBReleaseRequest,
	X2N_InitiatingMessage__value_PR_SeNBCounterCheckRequest,
	X2N_InitiatingMessage__value_PR_SgNBReconfigurationComplete,
	X2N_InitiatingMessage__value_PR_SgNBCounterCheckRequest,
	X2N_InitiatingMessage__value_PR_RRCTransfer,
	X2N_InitiatingMessage__value_PR_SecondaryRATDataUsageReport,
	X2N_InitiatingMessage__value_PR_SgNBActivityNotification,
	X2N_InitiatingMessage__value_PR_DataForwardingAddressIndication,
	X2N_InitiatingMessage__value_PR_GNBStatusIndication
} X2N_InitiatingMessage__value_PR;

/* X2N_InitiatingMessage */
typedef struct X2N_InitiatingMessage {
	X2N_ProcedureCode_t	 procedureCode;
	X2N_Criticality_t	 criticality;
	struct X2N_InitiatingMessage__value {
		X2N_InitiatingMessage__value_PR present;
		union X2N_InitiatingMessage__X2N_value_u {
			X2N_HandoverRequest_t	 HandoverRequest;
			X2N_ResetRequest_t	 ResetRequest;
			X2N_X2SetupRequest_t	 X2SetupRequest;
			X2N_ResourceStatusRequest_t	 ResourceStatusRequest;
			X2N_ENBConfigurationUpdate_t	 ENBConfigurationUpdate;
			X2N_MobilityChangeRequest_t	 MobilityChangeRequest;
			X2N_CellActivationRequest_t	 CellActivationRequest;
			X2N_SeNBAdditionRequest_t	 SeNBAdditionRequest;
			X2N_SeNBModificationRequest_t	 SeNBModificationRequest;
			X2N_SeNBModificationRequired_t	 SeNBModificationRequired;
			X2N_SeNBReleaseRequired_t	 SeNBReleaseRequired;
			X2N_X2RemovalRequest_t	 X2RemovalRequest;
			X2N_RetrieveUEContextRequest_t	 RetrieveUEContextRequest;
			X2N_SgNBAdditionRequest_t	 SgNBAdditionRequest;
			X2N_SgNBModificationRequest_t	 SgNBModificationRequest;
			X2N_SgNBModificationRequired_t	 SgNBModificationRequired;
			X2N_SgNBReleaseRequest_t	 SgNBReleaseRequest;
			X2N_SgNBReleaseRequired_t	 SgNBReleaseRequired;
			X2N_SgNBChangeRequired_t	 SgNBChangeRequired;
			X2N_ENDCX2SetupRequest_t	 ENDCX2SetupRequest;
			X2N_ENDCConfigurationUpdate_t	 ENDCConfigurationUpdate;
			X2N_ENDCCellActivationRequest_t	 ENDCCellActivationRequest;
			X2N_ENDCPartialResetRequired_t	 ENDCPartialResetRequired;
			X2N_EUTRANRCellResourceCoordinationRequest_t	 EUTRANRCellResourceCoordinationRequest;
			X2N_ENDCX2RemovalRequest_t	 ENDCX2RemovalRequest;
			X2N_SNStatusTransfer_t	 SNStatusTransfer;
			X2N_UEContextRelease_t	 UEContextRelease;
			X2N_HandoverCancel_t	 HandoverCancel;
			X2N_ErrorIndication_t	 ErrorIndication;
			X2N_ResourceStatusUpdate_t	 ResourceStatusUpdate;
			X2N_LoadInformation_t	 LoadInformation;
			X2N_PrivateMessage_t	 PrivateMessage;
			X2N_RLFIndication_t	 RLFIndication;
			X2N_HandoverReport_t	 HandoverReport;
			X2N_X2Release_t	 X2Release;
			X2N_X2APMessageTransfer_t	 X2APMessageTransfer;
			X2N_SeNBReconfigurationComplete_t	 SeNBReconfigurationComplete;
			X2N_SeNBReleaseRequest_t	 SeNBReleaseRequest;
			X2N_SeNBCounterCheckRequest_t	 SeNBCounterCheckRequest;
			X2N_SgNBReconfigurationComplete_t	 SgNBReconfigurationComplete;
			X2N_SgNBCounterCheckRequest_t	 SgNBCounterCheckRequest;
			X2N_RRCTransfer_t	 RRCTransfer;
			X2N_SecondaryRATDataUsageReport_t	 SecondaryRATDataUsageReport;
			X2N_SgNBActivityNotification_t	 SgNBActivityNotification;
			X2N_DataForwardingAddressIndication_t	 DataForwardingAddressIndication;
			X2N_GNBStatusIndication_t	 GNBStatusIndication;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} X2N_InitiatingMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2N_InitiatingMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_X2N_InitiatingMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_X2N_InitiatingMessage_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _X2N_InitiatingMessage_H_ */
#include <asn_internal.h>
