/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 */

#ifndef _X2N_ASN_CONSTANT_H
#define _X2N_ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define X2N_maxPrivateIEs (65535)
#define X2N_maxProtocolExtensions (65535)
#define X2N_maxProtocolIEs (65535)
#define X2N_maxEARFCN (65535)
#define X2N_maxEARFCNPlusOne (65536)
#define X2N_newmaxEARFCN (262143)
#define X2N_maxInterfaces (16)
#define X2N_maxCellineNB (256)
#define X2N_maxnoofBands (16)
#define X2N_maxnoofBearers (256)
#define X2N_maxNrOfErrors (256)
#define X2N_maxnoofPDCP_SN (16)
#define X2N_maxnoofEPLMNs (15)
#define X2N_maxnoofEPLMNsPlusOne (16)
#define X2N_maxnoofForbLACs (4096)
#define X2N_maxnoofForbTACs (4096)
#define X2N_maxnoofBPLMNs (6)
#define X2N_maxnoofNeighbours (512)
#define X2N_maxnoofPRBs (110)
#define X2N_maxPools (16)
#define X2N_maxnoofCells (16)
#define X2N_maxnoofMBSFN (8)
#define X2N_maxFailedMeasObjects (32)
#define X2N_maxnoofCellIDforMDT (32)
#define X2N_maxnoofTAforMDT (8)
#define X2N_maxnoofMBMSServiceAreaIdentities (256)
#define X2N_maxnoofMDTPLMNs (16)
#define X2N_maxnoofCoMPHypothesisSet (256)
#define X2N_maxnoofCoMPCells (32)
#define X2N_maxUEReport (128)
#define X2N_maxCellReport (9)
#define X2N_maxnoofPA (3)
#define X2N_maxCSIProcess (4)
#define X2N_maxCSIReport (2)
#define X2N_maxSubband (14)
#define X2N_maxofNRNeighbours (1024)
#define X2N_maxCellinengNB (16384)
#define X2N_maxnooftimeperiods (2)
#define X2N_maxnoofCellIDforQMC (32)
#define X2N_maxnoofTAforQMC (8)
#define X2N_maxnoofPLMNforQMC (16)
#define X2N_maxUEsinengNBDU (8192)
#define X2N_maxnoofProtectedResourcePatterns (16)
#define X2N_maxnoNRcellsSpectrumSharingWithE_UTRA (64)
#define X2N_maxnoofNrCellBands (32)
#define X2N_maxnoofBluetoothName (4)
#define X2N_maxnoofWLANName (4)


#ifdef __cplusplus
}
#endif

#endif /* _X2N_ASN_CONSTANT_H */
