/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_X2N_NRFreqInfo_H_
#define	_X2N_NRFreqInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct X2N_SULInformation;
struct X2N_ProtocolExtensionContainer;
struct X2N_FreqBandNrItem;

/* X2N_NRFreqInfo */
typedef struct X2N_NRFreqInfo {
	long	 nRARFCN;
	struct X2N_NRFreqInfo__freqBandListNr {
		A_SEQUENCE_OF(struct X2N_FreqBandNrItem) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} freqBandListNr;
	struct X2N_SULInformation	*sULInformation;	/* OPTIONAL */
	struct X2N_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} X2N_NRFreqInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2N_NRFreqInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_X2N_NRFreqInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_X2N_NRFreqInfo_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _X2N_NRFreqInfo_H_ */
#include <asn_internal.h>
