/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_X2N_UE_ContextInformationSeNBModReq_H_
#define	_X2N_UE_ContextInformationSeNBModReq_H_


#include <asn_application.h>

/* Including external dependencies */
#include "X2N_SeNBSecurityKey.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct X2N_UESecurityCapabilities;
struct X2N_UEAggregateMaximumBitRate;
struct X2N_E_RABs_ToBeAdded_List_ModReq;
struct X2N_E_RABs_ToBeModified_List_ModReq;
struct X2N_E_RABs_ToBeReleased_List_ModReq;
struct X2N_ProtocolExtensionContainer;

/* X2N_UE-ContextInformationSeNBModReq */
typedef struct X2N_UE_ContextInformationSeNBModReq {
	struct X2N_UESecurityCapabilities	*uE_SecurityCapabilities;	/* OPTIONAL */
	X2N_SeNBSecurityKey_t	*seNB_SecurityKey;	/* OPTIONAL */
	struct X2N_UEAggregateMaximumBitRate	*seNBUEAggregateMaximumBitRate;	/* OPTIONAL */
	struct X2N_E_RABs_ToBeAdded_List_ModReq	*e_RABs_ToBeAdded;	/* OPTIONAL */
	struct X2N_E_RABs_ToBeModified_List_ModReq	*e_RABs_ToBeModified;	/* OPTIONAL */
	struct X2N_E_RABs_ToBeReleased_List_ModReq	*e_RABs_ToBeReleased;	/* OPTIONAL */
	struct X2N_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} X2N_UE_ContextInformationSeNBModReq_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2N_UE_ContextInformationSeNBModReq;

#ifdef __cplusplus
}
#endif

#endif	/* _X2N_UE_ContextInformationSeNBModReq_H_ */
#include <asn_internal.h>
