/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_X2N_LastVisitedCell_Item_H_
#define	_X2N_LastVisitedCell_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "X2N_LastVisitedUTRANCellInformation.h"
#include "X2N_LastVisitedNGRANCellInformation.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum X2N_LastVisitedCell_Item_PR {
	X2N_LastVisitedCell_Item_PR_NOTHING,	/* No components present */
	X2N_LastVisitedCell_Item_PR_e_UTRAN_Cell,
	X2N_LastVisitedCell_Item_PR_uTRAN_Cell,
	X2N_LastVisitedCell_Item_PR_gERAN_Cell,
	/* Extensions may appear below */
	X2N_LastVisitedCell_Item_PR_nG_RAN_Cell
} X2N_LastVisitedCell_Item_PR;

/* Forward declarations */
struct X2N_LastVisitedEUTRANCellInformation;
struct X2N_LastVisitedGERANCellInformation;

/* X2N_LastVisitedCell-Item */
typedef struct X2N_LastVisitedCell_Item {
	X2N_LastVisitedCell_Item_PR present;
	union X2N_LastVisitedCell_Item_u {
		struct X2N_LastVisitedEUTRANCellInformation	*e_UTRAN_Cell;
		X2N_LastVisitedUTRANCellInformation_t	 uTRAN_Cell;
		struct X2N_LastVisitedGERANCellInformation	*gERAN_Cell;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		X2N_LastVisitedNGRANCellInformation_t	 nG_RAN_Cell;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} X2N_LastVisitedCell_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2N_LastVisitedCell_Item;
extern asn_CHOICE_specifics_t asn_SPC_X2N_LastVisitedCell_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_X2N_LastVisitedCell_Item_1[4];
extern asn_per_constraints_t asn_PER_type_X2N_LastVisitedCell_Item_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _X2N_LastVisitedCell_Item_H_ */
#include <asn_internal.h>
