/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_X2N_OffsetOfNbiotChannelNumberToEARFCN_H_
#define	_X2N_OffsetOfNbiotChannelNumberToEARFCN_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum X2N_OffsetOfNbiotChannelNumberToEARFCN {
	X2N_OffsetOfNbiotChannelNumberToEARFCN_minusTen	= 0,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_minusNine	= 1,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_minusEight	= 2,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_minusSeven	= 3,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_minusSix	= 4,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_minusFive	= 5,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_minusFour	= 6,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_minusThree	= 7,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_minusTwo	= 8,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_minusOne	= 9,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_minusZeroDotFive	= 10,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_zero	= 11,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_one	= 12,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_two	= 13,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_three	= 14,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_four	= 15,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_five	= 16,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_six	= 17,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_seven	= 18,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_eight	= 19,
	X2N_OffsetOfNbiotChannelNumberToEARFCN_nine	= 20
	/*
	 * Enumeration is extensible
	 */
} e_X2N_OffsetOfNbiotChannelNumberToEARFCN;

/* X2N_OffsetOfNbiotChannelNumberToEARFCN */
typedef long	 X2N_OffsetOfNbiotChannelNumberToEARFCN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2N_OffsetOfNbiotChannelNumberToEARFCN;
asn_struct_free_f X2N_OffsetOfNbiotChannelNumberToEARFCN_free;
asn_struct_print_f X2N_OffsetOfNbiotChannelNumberToEARFCN_print;
asn_constr_check_f X2N_OffsetOfNbiotChannelNumberToEARFCN_constraint;
ber_type_decoder_f X2N_OffsetOfNbiotChannelNumberToEARFCN_decode_ber;
der_type_encoder_f X2N_OffsetOfNbiotChannelNumberToEARFCN_encode_der;
xer_type_decoder_f X2N_OffsetOfNbiotChannelNumberToEARFCN_decode_xer;
xer_type_encoder_f X2N_OffsetOfNbiotChannelNumberToEARFCN_encode_xer;
per_type_decoder_f X2N_OffsetOfNbiotChannelNumberToEARFCN_decode_uper;
per_type_encoder_f X2N_OffsetOfNbiotChannelNumberToEARFCN_encode_uper;
per_type_decoder_f X2N_OffsetOfNbiotChannelNumberToEARFCN_decode_aper;
per_type_encoder_f X2N_OffsetOfNbiotChannelNumberToEARFCN_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _X2N_OffsetOfNbiotChannelNumberToEARFCN_H_ */
#include <asn_internal.h>
