/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_X2N_E_RABs_ToBeReleased_RelConfItem_H_
#define	_X2N_E_RABs_ToBeReleased_RelConfItem_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum X2N_E_RABs_ToBeReleased_RelConfItem_PR {
	X2N_E_RABs_ToBeReleased_RelConfItem_PR_NOTHING,	/* No components present */
	X2N_E_RABs_ToBeReleased_RelConfItem_PR_sCG_Bearer,
	X2N_E_RABs_ToBeReleased_RelConfItem_PR_split_Bearer
	/* Extensions may appear below */
	
} X2N_E_RABs_ToBeReleased_RelConfItem_PR;

/* Forward declarations */
struct X2N_E_RABs_ToBeReleased_RelConfItem_SCG_Bearer;
struct X2N_E_RABs_ToBeReleased_RelConfItem_Split_Bearer;

/* X2N_E-RABs-ToBeReleased-RelConfItem */
typedef struct X2N_E_RABs_ToBeReleased_RelConfItem {
	X2N_E_RABs_ToBeReleased_RelConfItem_PR present;
	union X2N_E_RABs_ToBeReleased_RelConfItem_u {
		struct X2N_E_RABs_ToBeReleased_RelConfItem_SCG_Bearer	*sCG_Bearer;
		struct X2N_E_RABs_ToBeReleased_RelConfItem_Split_Bearer	*split_Bearer;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} X2N_E_RABs_ToBeReleased_RelConfItem_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2N_E_RABs_ToBeReleased_RelConfItem;

#ifdef __cplusplus
}
#endif

#endif	/* _X2N_E_RABs_ToBeReleased_RelConfItem_H_ */
#include <asn_internal.h>
