/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_X2N_UE_ContextReferenceAtSgNB_H_
#define	_X2N_UE_ContextReferenceAtSgNB_H_


#include <asn_application.h>

/* Including external dependencies */
#include "X2N_GlobalGNB-ID.h"
#include "X2N_SgNB-UE-X2AP-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct X2N_ProtocolExtensionContainer;

/* X2N_UE-ContextReferenceAtSgNB */
typedef struct X2N_UE_ContextReferenceAtSgNB {
	X2N_GlobalGNB_ID_t	 source_GlobalSgNB_ID;
	X2N_SgNB_UE_X2AP_ID_t	 sgNB_UE_X2AP_ID;
	struct X2N_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} X2N_UE_ContextReferenceAtSgNB_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2N_UE_ContextReferenceAtSgNB;

#ifdef __cplusplus
}
#endif

#endif	/* _X2N_UE_ContextReferenceAtSgNB_H_ */
#include <asn_internal.h>
