/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_X2N_M6delay_threshold_H_
#define	_X2N_M6delay_threshold_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum X2N_M6delay_threshold {
	X2N_M6delay_threshold_ms30	= 0,
	X2N_M6delay_threshold_ms40	= 1,
	X2N_M6delay_threshold_ms50	= 2,
	X2N_M6delay_threshold_ms60	= 3,
	X2N_M6delay_threshold_ms70	= 4,
	X2N_M6delay_threshold_ms80	= 5,
	X2N_M6delay_threshold_ms90	= 6,
	X2N_M6delay_threshold_ms100	= 7,
	X2N_M6delay_threshold_ms150	= 8,
	X2N_M6delay_threshold_ms300	= 9,
	X2N_M6delay_threshold_ms500	= 10,
	X2N_M6delay_threshold_ms750	= 11
	/*
	 * Enumeration is extensible
	 */
} e_X2N_M6delay_threshold;

/* X2N_M6delay-threshold */
typedef long	 X2N_M6delay_threshold_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_X2N_M6delay_threshold_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_X2N_M6delay_threshold;
extern const asn_INTEGER_specifics_t asn_SPC_M6delay_threshold_specs_1;
asn_struct_free_f M6delay_threshold_free;
asn_struct_print_f M6delay_threshold_print;
asn_constr_check_f M6delay_threshold_constraint;
ber_type_decoder_f M6delay_threshold_decode_ber;
der_type_encoder_f M6delay_threshold_encode_der;
xer_type_decoder_f M6delay_threshold_decode_xer;
xer_type_encoder_f M6delay_threshold_encode_xer;
per_type_decoder_f M6delay_threshold_decode_uper;
per_type_encoder_f M6delay_threshold_encode_uper;
per_type_decoder_f M6delay_threshold_decode_aper;
per_type_encoder_f M6delay_threshold_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _X2N_M6delay_threshold_H_ */
#include <asn_internal.h>
