/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#include "X2N_CoMPInformationStartTime.h"

#include "X2N_ProtocolExtensionContainer.h"
static int
memb_X2N_startSFN_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1023)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_X2N_startSubframeNumber_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 9)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_memb_X2N_startSFN_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  10,  10,  0,  1023 }	/* (0..1023,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_X2N_startSubframeNumber_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  9 }	/* (0..9,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_X2N_CoMPInformationStartTime_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (SIZE(0..1)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_X2N_Member_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_CoMPInformationStartTime__Member, startSFN),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_X2N_startSFN_constr_3,  memb_X2N_startSFN_constraint_2 },
		0, 0, /* No default value */
		"startSFN"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_CoMPInformationStartTime__Member, startSubframeNumber),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_X2N_startSubframeNumber_constr_4,  memb_X2N_startSubframeNumber_constraint_2 },
		0, 0, /* No default value */
		"startSubframeNumber"
		},
	{ ATF_POINTER, 1, offsetof(struct X2N_CoMPInformationStartTime__Member, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_X2N_ProtocolExtensionContainer_8231P120,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_X2N_Member_oms_2[] = { 2 };
static const ber_tlv_tag_t asn_DEF_X2N_Member_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_X2N_Member_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* startSFN */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* startSubframeNumber */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
static asn_SEQUENCE_specifics_t asn_SPC_X2N_Member_specs_2 = {
	sizeof(struct X2N_CoMPInformationStartTime__Member),
	offsetof(struct X2N_CoMPInformationStartTime__Member, _asn_ctx),
	asn_MAP_X2N_Member_tag2el_2,
	3,	/* Count of tags in the map */
	asn_MAP_X2N_Member_oms_2,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_X2N_Member_2 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_Member_tags_2,
	sizeof(asn_DEF_X2N_Member_tags_2)
		/sizeof(asn_DEF_X2N_Member_tags_2[0]), /* 1 */
	asn_DEF_X2N_Member_tags_2,	/* Same as above */
	sizeof(asn_DEF_X2N_Member_tags_2)
		/sizeof(asn_DEF_X2N_Member_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_Member_2,
	3,	/* Elements count */
	&asn_SPC_X2N_Member_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_X2N_CoMPInformationStartTime_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_X2N_Member_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_X2N_CoMPInformationStartTime_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_X2N_CoMPInformationStartTime_specs_1 = {
	sizeof(struct X2N_CoMPInformationStartTime),
	offsetof(struct X2N_CoMPInformationStartTime, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_X2N_CoMPInformationStartTime = {
	"CoMPInformationStartTime",
	"CoMPInformationStartTime",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_X2N_CoMPInformationStartTime_tags_1,
	sizeof(asn_DEF_X2N_CoMPInformationStartTime_tags_1)
		/sizeof(asn_DEF_X2N_CoMPInformationStartTime_tags_1[0]), /* 1 */
	asn_DEF_X2N_CoMPInformationStartTime_tags_1,	/* Same as above */
	sizeof(asn_DEF_X2N_CoMPInformationStartTime_tags_1)
		/sizeof(asn_DEF_X2N_CoMPInformationStartTime_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_X2N_CoMPInformationStartTime_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_X2N_CoMPInformationStartTime_1,
	1,	/* Single element */
	&asn_SPC_X2N_CoMPInformationStartTime_specs_1	/* Additional specs */
};

