/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-Containers"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_X2N_PrivateIE_Field_H_
#define	_X2N_PrivateIE_Field_H_


#include <asn_application.h>

/* Including external dependencies */
#include "X2N_PrivateIE-ID.h"
#include "X2N_Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum X2N_PrivateMessage_IEs__value_PR {
	X2N_PrivateMessage_IEs__value_PR_NOTHING	/* No components present */
	
} X2N_PrivateMessage_IEs__value_PR;

/* X2N_PrivateIE-Field */
typedef struct X2N_PrivateMessage_IEs {
	X2N_PrivateIE_ID_t	 id;
	X2N_Criticality_t	 criticality;
	struct X2N_PrivateMessage_IEs__value {
		X2N_PrivateMessage_IEs__value_PR present;
		union X2N_PrivateMessage_IEs__X2N_value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} X2N_PrivateMessage_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2N_PrivateMessage_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_X2N_PrivateMessage_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_X2N_PrivateMessage_IEs_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _X2N_PrivateIE_Field_H_ */
#include <asn_internal.h>
