/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_X2N_AreaScopeOfMDT_H_
#define	_X2N_AreaScopeOfMDT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum X2N_AreaScopeOfMDT_PR {
	X2N_AreaScopeOfMDT_PR_NOTHING,	/* No components present */
	X2N_AreaScopeOfMDT_PR_cellBased,
	X2N_AreaScopeOfMDT_PR_tABased,
	X2N_AreaScopeOfMDT_PR_pLMNWide,
	/* Extensions may appear below */
	X2N_AreaScopeOfMDT_PR_tAIBased
} X2N_AreaScopeOfMDT_PR;

/* Forward declarations */
struct X2N_CellBasedMDT;
struct X2N_TABasedMDT;
struct X2N_TAIBasedMDT;

/* X2N_AreaScopeOfMDT */
typedef struct X2N_AreaScopeOfMDT {
	X2N_AreaScopeOfMDT_PR present;
	union X2N_AreaScopeOfMDT_u {
		struct X2N_CellBasedMDT	*cellBased;
		struct X2N_TABasedMDT	*tABased;
		NULL_t	 pLMNWide;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		struct X2N_TAIBasedMDT	*tAIBased;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} X2N_AreaScopeOfMDT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2N_AreaScopeOfMDT;
extern asn_CHOICE_specifics_t asn_SPC_X2N_AreaScopeOfMDT_specs_1;
extern asn_TYPE_member_t asn_MBR_X2N_AreaScopeOfMDT_1[4];
extern asn_per_constraints_t asn_PER_type_X2N_AreaScopeOfMDT_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _X2N_AreaScopeOfMDT_H_ */
#include <asn_internal.h>
