/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-Containers"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#include "X2N_ProtocolIE-Single-Container.h"

/*
 * This type is implemented using X2N_E_RABs_ToBeSetup_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_Admitted_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_SubjectToStatusTransfer_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_CellInformation_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_CellToReport_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_MeasurementInitiationResult_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_MeasurementFailureCause_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_CompleteFailureCauseInformation_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_CellMeasurementResult_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeAdded_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_Admitted_ToBeAdded_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeAdded_ModReqItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeModified_ModReqItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeReleased_ModReqItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_Admitted_ToBeAdded_ModAckItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_Admitted_ToBeModified_ModAckItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_Admitted_ToBeReleased_ModAckItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeReleased_ModReqdItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeReleased_RelReqItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeReleased_RelConfItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_SubjectToCounterCheckItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeSetupRetrieve_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeAdded_SgNBAddReq_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeAdded_SgNBModReq_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeModified_SgNBModReq_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeReleased_SgNBModReq_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_Admitted_ToBeAdded_SgNBModAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_Admitted_ToBeModified_SgNBModAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_Admitted_ToBeReleased_SgNBModAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeReleased_SgNBModReqd_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeModified_SgNBModReqd_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_AdmittedToBeModified_SgNBModConf_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeReleased_SgNBRelReq_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_Admitted_ToBeReleased_SgNBRelReqAck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeReleased_SgNBRelReqd_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeReleased_SgNBRelConf_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_SubjectToSgNBCounterCheck_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_ToBeReleased_SgNBChaConf_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABs_DataForwardingAddress_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RAB_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_E_RABUsageReport_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using X2N_SecondaryRATUsageReport_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P0 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P0_tags_1,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P0_tags_1)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P0_tags_1[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P0_tags_1)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P0_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeSetup_ItemIEs_1,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeSetup_ItemIEs_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P1 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P1_tags_2,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P1_tags_2)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P1_tags_2[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P1_tags_2,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P1_tags_2)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P1_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_Admitted_ItemIEs_5,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_Admitted_ItemIEs_specs_5	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P2_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P2 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P2_tags_3,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P2_tags_3)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P2_tags_3[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P2_tags_3,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P2_tags_3)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P2_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_SubjectToStatusTransfer_ItemIEs_9,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_SubjectToStatusTransfer_ItemIEs_specs_9	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P3_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P3 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P3_tags_4,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P3_tags_4)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P3_tags_4[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P3_tags_4,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P3_tags_4)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P3_tags_4[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_CellInformation_ItemIEs_13,
	3,	/* Elements count */
	&asn_SPC_X2N_CellInformation_ItemIEs_specs_13	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P4_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P4 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P4_tags_5,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P4_tags_5)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P4_tags_5[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P4_tags_5,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P4_tags_5)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P4_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_CellToReport_ItemIEs_17,
	3,	/* Elements count */
	&asn_SPC_X2N_CellToReport_ItemIEs_specs_17	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P5_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P5 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P5_tags_6,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P5_tags_6)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P5_tags_6[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P5_tags_6,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P5_tags_6)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P5_tags_6[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_MeasurementInitiationResult_ItemIEs_21,
	3,	/* Elements count */
	&asn_SPC_X2N_MeasurementInitiationResult_ItemIEs_specs_21	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P6_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P6 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P6_tags_7,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P6_tags_7)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P6_tags_7[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P6_tags_7,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P6_tags_7)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P6_tags_7[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_MeasurementFailureCause_ItemIEs_25,
	3,	/* Elements count */
	&asn_SPC_X2N_MeasurementFailureCause_ItemIEs_specs_25	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P7_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P7 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P7_tags_8,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P7_tags_8)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P7_tags_8[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P7_tags_8,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P7_tags_8)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P7_tags_8[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_CompleteFailureCauseInformation_ItemIEs_29,
	3,	/* Elements count */
	&asn_SPC_X2N_CompleteFailureCauseInformation_ItemIEs_specs_29	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P8_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P8 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P8_tags_9,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P8_tags_9)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P8_tags_9[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P8_tags_9,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P8_tags_9)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P8_tags_9[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_CellMeasurementResult_ItemIEs_33,
	3,	/* Elements count */
	&asn_SPC_X2N_CellMeasurementResult_ItemIEs_specs_33	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P9_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P9 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P9_tags_10,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P9_tags_10)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P9_tags_10[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P9_tags_10,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P9_tags_10)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P9_tags_10[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeAdded_ItemIEs_37,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeAdded_ItemIEs_specs_37	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P10_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P10 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P10_tags_11,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P10_tags_11)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P10_tags_11[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P10_tags_11,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P10_tags_11)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P10_tags_11[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_Admitted_ToBeAdded_ItemIEs_41,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_Admitted_ToBeAdded_ItemIEs_specs_41	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P11_tags_12[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P11 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P11_tags_12,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P11_tags_12)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P11_tags_12[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P11_tags_12,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P11_tags_12)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P11_tags_12[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeAdded_ModReqItemIEs_45,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeAdded_ModReqItemIEs_specs_45	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P12_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P12 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P12_tags_13,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P12_tags_13)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P12_tags_13[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P12_tags_13,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P12_tags_13)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P12_tags_13[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeModified_ModReqItemIEs_49,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeModified_ModReqItemIEs_specs_49	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P13_tags_14[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P13 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P13_tags_14,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P13_tags_14)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P13_tags_14[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P13_tags_14,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P13_tags_14)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P13_tags_14[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeReleased_ModReqItemIEs_53,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeReleased_ModReqItemIEs_specs_53	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P14_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P14 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P14_tags_15,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P14_tags_15)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P14_tags_15[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P14_tags_15,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P14_tags_15)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P14_tags_15[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_Admitted_ToBeAdded_ModAckItemIEs_57,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_Admitted_ToBeAdded_ModAckItemIEs_specs_57	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P15_tags_16[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P15 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P15_tags_16,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P15_tags_16)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P15_tags_16[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P15_tags_16,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P15_tags_16)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P15_tags_16[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_Admitted_ToBeModified_ModAckItemIEs_61,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_Admitted_ToBeModified_ModAckItemIEs_specs_61	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P16_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P16 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P16_tags_17,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P16_tags_17)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P16_tags_17[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P16_tags_17,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P16_tags_17)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P16_tags_17[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_Admitted_ToBeReleased_ModAckItemIEs_65,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_Admitted_ToBeReleased_ModAckItemIEs_specs_65	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P17_tags_18[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P17 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P17_tags_18,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P17_tags_18)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P17_tags_18[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P17_tags_18,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P17_tags_18)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P17_tags_18[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeReleased_ModReqdItemIEs_69,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeReleased_ModReqdItemIEs_specs_69	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P18_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P18 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P18_tags_19,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P18_tags_19)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P18_tags_19[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P18_tags_19,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P18_tags_19)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P18_tags_19[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeReleased_RelReqItemIEs_73,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeReleased_RelReqItemIEs_specs_73	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P19_tags_20[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P19 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P19_tags_20,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P19_tags_20)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P19_tags_20[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P19_tags_20,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P19_tags_20)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P19_tags_20[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeReleased_RelConfItemIEs_77,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeReleased_RelConfItemIEs_specs_77	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P20_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P20 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P20_tags_21,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P20_tags_21)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P20_tags_21[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P20_tags_21,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P20_tags_21)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P20_tags_21[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_SubjectToCounterCheckItemIEs_81,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_SubjectToCounterCheckItemIEs_specs_81	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P21_tags_22[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P21 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P21_tags_22,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P21_tags_22)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P21_tags_22[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P21_tags_22,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P21_tags_22)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P21_tags_22[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeSetupRetrieve_ItemIEs_85,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeSetupRetrieve_ItemIEs_specs_85	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P22_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P22 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P22_tags_23,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P22_tags_23)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P22_tags_23[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P22_tags_23,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P22_tags_23)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P22_tags_23[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeAdded_SgNBAddReq_ItemIEs_89,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeAdded_SgNBAddReq_ItemIEs_specs_89	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P23_tags_24[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P23 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P23_tags_24,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P23_tags_24)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P23_tags_24[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P23_tags_24,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P23_tags_24)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P23_tags_24[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_ItemIEs_93,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_Admitted_ToBeAdded_SgNBAddReqAck_ItemIEs_specs_93	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P24_tags_25[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P24 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P24_tags_25,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P24_tags_25)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P24_tags_25[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P24_tags_25,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P24_tags_25)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P24_tags_25[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeAdded_SgNBModReq_ItemIEs_97,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeAdded_SgNBModReq_ItemIEs_specs_97	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P25_tags_26[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P25 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P25_tags_26,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P25_tags_26)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P25_tags_26[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P25_tags_26,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P25_tags_26)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P25_tags_26[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeModified_SgNBModReq_ItemIEs_101,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeModified_SgNBModReq_ItemIEs_specs_101	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P26_tags_27[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P26 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P26_tags_27,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P26_tags_27)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P26_tags_27[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P26_tags_27,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P26_tags_27)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P26_tags_27[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeReleased_SgNBModReq_ItemIEs_105,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeReleased_SgNBModReq_ItemIEs_specs_105	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P27_tags_28[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P27 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P27_tags_28,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P27_tags_28)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P27_tags_28[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P27_tags_28,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P27_tags_28)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P27_tags_28[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_Admitted_ToBeAdded_SgNBModAck_ItemIEs_109,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_Admitted_ToBeAdded_SgNBModAck_ItemIEs_specs_109	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P28_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P28 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P28_tags_29,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P28_tags_29)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P28_tags_29[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P28_tags_29,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P28_tags_29)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P28_tags_29[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_Admitted_ToBeModified_SgNBModAck_ItemIEs_113,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_Admitted_ToBeModified_SgNBModAck_ItemIEs_specs_113	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P29_tags_30[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P29 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P29_tags_30,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P29_tags_30)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P29_tags_30[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P29_tags_30,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P29_tags_30)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P29_tags_30[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_Admitted_ToBeReleased_SgNBModAck_ItemIEs_117,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_Admitted_ToBeReleased_SgNBModAck_ItemIEs_specs_117	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P30_tags_31[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P30 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P30_tags_31,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P30_tags_31)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P30_tags_31[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P30_tags_31,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P30_tags_31)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P30_tags_31[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeReleased_SgNBModReqd_ItemIEs_121,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeReleased_SgNBModReqd_ItemIEs_specs_121	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P31_tags_32[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P31 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P31_tags_32,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P31_tags_32)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P31_tags_32[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P31_tags_32,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P31_tags_32)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P31_tags_32[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeModified_SgNBModReqd_ItemIEs_125,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeModified_SgNBModReqd_ItemIEs_specs_125	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P32_tags_33[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P32 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P32_tags_33,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P32_tags_33)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P32_tags_33[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P32_tags_33,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P32_tags_33)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P32_tags_33[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_AdmittedToBeModified_SgNBModConf_ItemIEs_129,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_AdmittedToBeModified_SgNBModConf_ItemIEs_specs_129	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P33_tags_34[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P33 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P33_tags_34,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P33_tags_34)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P33_tags_34[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P33_tags_34,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P33_tags_34)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P33_tags_34[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeReleased_SgNBRelReq_ItemIEs_133,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeReleased_SgNBRelReq_ItemIEs_specs_133	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P34_tags_35[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P34 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P34_tags_35,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P34_tags_35)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P34_tags_35[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P34_tags_35,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P34_tags_35)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P34_tags_35[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_Admitted_ToBeReleased_SgNBRelReqAck_ItemIEs_137,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_Admitted_ToBeReleased_SgNBRelReqAck_ItemIEs_specs_137	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P35_tags_36[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P35 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P35_tags_36,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P35_tags_36)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P35_tags_36[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P35_tags_36,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P35_tags_36)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P35_tags_36[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeReleased_SgNBRelReqd_ItemIEs_141,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeReleased_SgNBRelReqd_ItemIEs_specs_141	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P36_tags_37[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P36 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P36_tags_37,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P36_tags_37)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P36_tags_37[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P36_tags_37,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P36_tags_37)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P36_tags_37[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeReleased_SgNBRelConf_ItemIEs_145,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeReleased_SgNBRelConf_ItemIEs_specs_145	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P37_tags_38[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P37 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P37_tags_38,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P37_tags_38)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P37_tags_38[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P37_tags_38,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P37_tags_38)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P37_tags_38[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_SubjectToSgNBCounterCheck_ItemIEs_149,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_SubjectToSgNBCounterCheck_ItemIEs_specs_149	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P38_tags_39[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P38 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P38_tags_39,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P38_tags_39)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P38_tags_39[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P38_tags_39,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P38_tags_39)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P38_tags_39[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_ToBeReleased_SgNBChaConf_ItemIEs_153,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_ToBeReleased_SgNBChaConf_ItemIEs_specs_153	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P39_tags_40[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P39 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P39_tags_40,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P39_tags_40)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P39_tags_40[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P39_tags_40,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P39_tags_40)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P39_tags_40[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABs_DataForwardingAddress_ItemIEs_157,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABs_DataForwardingAddress_ItemIEs_specs_157	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P40_tags_41[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P40 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P40_tags_41,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P40_tags_41)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P40_tags_41[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P40_tags_41,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P40_tags_41)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P40_tags_41[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RAB_ItemIEs_161,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RAB_ItemIEs_specs_161	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P41_tags_42[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P41 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P41_tags_42,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P41_tags_42)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P41_tags_42[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P41_tags_42,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P41_tags_42)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P41_tags_42[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_E_RABUsageReport_ItemIEs_165,
	3,	/* Elements count */
	&asn_SPC_X2N_E_RABUsageReport_ItemIEs_specs_165	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P42_tags_43[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_X2N_ProtocolIE_Single_Container_8183P42 = {
	"ProtocolIE-Single-Container",
	"ProtocolIE-Single-Container",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P42_tags_43,
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P42_tags_43)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P42_tags_43[0]), /* 1 */
	asn_DEF_X2N_ProtocolIE_Single_Container_8183P42_tags_43,	/* Same as above */
	sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P42_tags_43)
		/sizeof(asn_DEF_X2N_ProtocolIE_Single_Container_8183P42_tags_43[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_SecondaryRATUsageReport_ItemIEs_169,
	3,	/* Elements count */
	&asn_SPC_X2N_SecondaryRATUsageReport_ItemIEs_specs_169	/* Additional specs */
};

