/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-PDU-Contents"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#include "X2N_FDD-InfoServedNRCell-Information.h"

#include "X2N_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_X2N_FDD_InfoServedNRCell_Information_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_FDD_InfoServedNRCell_Information, ul_NRFreqInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_X2N_NRFreqInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-NRFreqInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_FDD_InfoServedNRCell_Information, dl_NRFreqInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_X2N_NRFreqInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dl-NRFreqInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_FDD_InfoServedNRCell_Information, ul_NR_TxBW),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_X2N_NR_TxBW,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ul-NR-TxBW"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X2N_FDD_InfoServedNRCell_Information, dl_NR_TxBW),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_X2N_NR_TxBW,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dl-NR-TxBW"
		},
	{ ATF_POINTER, 1, offsetof(struct X2N_FDD_InfoServedNRCell_Information, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_X2N_ProtocolExtensionContainer_8231P93,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_X2N_FDD_InfoServedNRCell_Information_oms_1[] = { 4 };
static const ber_tlv_tag_t asn_DEF_X2N_FDD_InfoServedNRCell_Information_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_X2N_FDD_InfoServedNRCell_Information_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ul-NRFreqInfo */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dl-NRFreqInfo */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ul-NR-TxBW */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* dl-NR-TxBW */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_X2N_FDD_InfoServedNRCell_Information_specs_1 = {
	sizeof(struct X2N_FDD_InfoServedNRCell_Information),
	offsetof(struct X2N_FDD_InfoServedNRCell_Information, _asn_ctx),
	asn_MAP_X2N_FDD_InfoServedNRCell_Information_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_X2N_FDD_InfoServedNRCell_Information_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_X2N_FDD_InfoServedNRCell_Information = {
	"FDD-InfoServedNRCell-Information",
	"FDD-InfoServedNRCell-Information",
	&asn_OP_SEQUENCE,
	asn_DEF_X2N_FDD_InfoServedNRCell_Information_tags_1,
	sizeof(asn_DEF_X2N_FDD_InfoServedNRCell_Information_tags_1)
		/sizeof(asn_DEF_X2N_FDD_InfoServedNRCell_Information_tags_1[0]), /* 1 */
	asn_DEF_X2N_FDD_InfoServedNRCell_Information_tags_1,	/* Same as above */
	sizeof(asn_DEF_X2N_FDD_InfoServedNRCell_Information_tags_1)
		/sizeof(asn_DEF_X2N_FDD_InfoServedNRCell_Information_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_X2N_FDD_InfoServedNRCell_Information_1,
	5,	/* Elements count */
	&asn_SPC_X2N_FDD_InfoServedNRCell_Information_specs_1	/* Additional specs */
};

