/*
 * Generated by asn1c-0.9.29 n1 (http://lionet.info/asn1c)
 * From ASN.1 module "X2AP-IEs"
 * 	found in "../../asn_defs/asn1/x2ap-15-04.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -gen-PER -no-gen-OER`
 */

#ifndef	_X2N_AreaScopeOfQMC_H_
#define	_X2N_AreaScopeOfQMC_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum X2N_AreaScopeOfQMC_PR {
	X2N_AreaScopeOfQMC_PR_NOTHING,	/* No components present */
	X2N_AreaScopeOfQMC_PR_cellBased,
	X2N_AreaScopeOfQMC_PR_tABased,
	X2N_AreaScopeOfQMC_PR_tAIBased,
	X2N_AreaScopeOfQMC_PR_pLMNAreaBased
	/* Extensions may appear below */
	
} X2N_AreaScopeOfQMC_PR;

/* Forward declarations */
struct X2N_CellBasedQMC;
struct X2N_TABasedQMC;
struct X2N_TAIBasedQMC;
struct X2N_PLMNAreaBasedQMC;

/* X2N_AreaScopeOfQMC */
typedef struct X2N_AreaScopeOfQMC {
	X2N_AreaScopeOfQMC_PR present;
	union X2N_AreaScopeOfQMC_u {
		struct X2N_CellBasedQMC	*cellBased;
		struct X2N_TABasedQMC	*tABased;
		struct X2N_TAIBasedQMC	*tAIBased;
		struct X2N_PLMNAreaBasedQMC	*pLMNAreaBased;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} X2N_AreaScopeOfQMC_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_X2N_AreaScopeOfQMC;
extern asn_CHOICE_specifics_t asn_SPC_X2N_AreaScopeOfQMC_specs_1;
extern asn_TYPE_member_t asn_MBR_X2N_AreaScopeOfQMC_1[4];
extern asn_per_constraints_t asn_PER_type_X2N_AreaScopeOfQMC_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _X2N_AreaScopeOfQMC_H_ */
#include <asn_internal.h>
